### ISSUE TITLE
Turbografx CD: emustation is unable to read the synopsis txt file

### ISSUE THREAD

**Issue by evertonstz** [Rocky5/XBMC-Emustation#10]
Hi Rocky5, I'm having trouble getting the Turbografx CD synopsis to show, the dumps for the tgcd are in the CUE/ISO/WAV format and the cover art, matching the name of the cue, is working. The synopsis in other hand isn't being shown, the txt has the same name as cue of course, and the text inside is valid, as I copied it to a random psx game's synopsis and it works fine.

EDIT: just to test I tried with the Turbografx 16 too, I get the same problem with the synopsis not showing, but the image showing fine

EDIT2: don't know if this one is a bug, but for the famicon you have to put the roms in the .emustation\roms\famicon folder, the images go into the .emustation\media\famicon folder too, but the synopsis txt files at .emustation\synopsis\famicon they won't work, you have to put them at .emustation\synopsis\nes in order to get the synopsis to show for the famicon system,

**Comment by evertonstz** [comment]
> Issue 1 - code is fine if the file name matches a synopsis files txt name (pce-cd) it will use it. It should extract all the synopsis files from the included zip. (tg-cd and pce-cd are the same system)

Yes, renaming the synopsis folder from tg-cd to pce-cd solved the problem. I think the problem lies in the _.emustation\scripts\synopsis maker\default.py_ for Issue 1 and 2 tho: I wasn't using the txts you provide bundled with emustation, since I have all my roms scrapped in my pc I was just feeding my gamelist.xml to the synopsis maker, what is happening is that I was feeding the xml to the script and saying it was from tg-cd, the script would normally parse the gamelist and output the txt to a tg-cd folder instead to a pce-cd folder. Same with tg-16, it was not outputing the txts to a pce-16 folder, and the famicon also wasn't outputing to a nes folder.
I don't know if this is intentional, but would not be better to output the correct folder name when using synopsis maker? I'm manually runing the script via the file manager and manually selecting the system, tho, so I'm not sure if that's how that script is supposed to be used.

**Comment by Rocky5** [comment]
Yeah that’s an oversight on my part sorry, will update the synopsis script to output to the alt folders. 

Or I may just include tg stuff and famicom and update the scan script to use them instead of selecting the later (EU) names.
