### ISSUE TITLE
flicker filter bug

### ISSUE THREAD

**Issue by filevans** [Rocky5/XBMC-Emustation#100]
hello, sorry this bug report is for unleashx that comes with the rocky5 softmodding tool but that repository doesn't have an issues tab and I didn't know where else to report it

this version of unleashx has a bug with the flicker filter, after setting it to 0, saving and restarting, flicker filter comes back on, although the setting still says "0", i've tried it on multiple xboxes, same thing, and the bug doesn't happen on other versions of unleashx. 

this happens on video mode 480i at least, nkpatcher flicker filter left to default 

thank you

**Comment by Rocky5** [comment]
Not much we can do without the source code to unleashx, you can download an older version and see if it has the same issue or it doesn’t.

**Comment by filevans** [comment]
It's only the version of unleashx that comes with Rocky5 softmodding tool that it happens on, so I thought maybe you had patched it or made your own build

**Comment by Rocky5** [comment]
> It's only the version of unleashx that comes with Rocky5 softmodding tool that it happens on, so I thought maybe you had patched it or made your own build

The version with the softmod was the last version of unleashx released to the public. I just fixed the FTP issue & moved the zip to the end of the file so it’s easier for people to replace. 

The ftp issue is why everyone else used the older version (before the avalaunch ftp code was added)
