### ISSUE TITLE
SD Resolution support - UI Settings 

### ISSUE THREAD

**Issue by loggio** [Rocky5/XBMC-Emustation#101]
Hi there, 

Been a while since i jumped back on my XBOX to play around with SD support. I just updated XBMC-Emustation, i noticed there is now option in UI settings "SD Resolution Support" 

Using PAL SD resolution of 720x576 from stock install everything looks fine, the way i modified the carbon skin to work with SD resolutions. 
But when I toggle this option on, the XBOX reboots and the text/images are all small and hard to read. Switching it back off restores SD resolution to how they should be. 

Do you have this toggle backwards by any chance? or ... what is this toggle suppose to do exactly?

**Comment by Rocky5** [comment]
It’s under the disable list, you will notice there is a disabled and enable list.

**Comment by loggio** [comment]
ah yes, of course. The enable/disable titles are missing from the SD xml files.

**Comment by Rocky5** [comment]
> ah yes, of course. The enable/disable titles are missing from the SD xml files.

Oh 🙈 I don’t use the SD stuff so never noticed 🙈

**Comment by Rocky5** [comment]
Would you like to update the SD downloader files? As I have changed the layout and also changed all the colour names. (added a coupe more removed some)

As the downloader will have not work correctly without the changes. 
[SD Downloader Files.zip](https://github.com/Rocky5/XBMC-Emustation/files/13981581/SD.Downloader.Files.zip)

**Comment by loggio** [comment]
Yeah sure. Will take a look when I get a minute. Away camping at the moment. Prob late next week.

**Comment by loggio** [comment]
Updated as per request. Thanks for the templates. Makes life easier. 
[SD Downloader Files_Updated.zip](https://github.com/Rocky5/XBMC-Emustation/files/14033732/SD.Downloader.Files_Updated.zip)

**Comment by Rocky5** [comment]
> Updated as per request. Thanks for the templates. Makes life easier. [SD Downloader Files_Updated.zip](https://github.com/Rocky5/XBMC-Emustation/files/14033732/SD.Downloader.Files_Updated.zip)

Thank you.

**Comment by loggio** [comment]
Hey, did you get a chance to update these files? i just did an over the air update of emustation urldownloader and the pal/ntsc URLdownload xmls are not what i sent you

**Comment by Rocky5** [comment]
> you

Yup, I downloaded your zip and extracted the files and overwrite mine.

**Comment by loggio** [comment]
okay, somethings not right. I do a force update and the left hand menu is off alignment on y axis by about 60 and the update page is out of alignment. The _Script_URLDownloader.xml in the ntsc folder of the simple theme is showing 1280x720.  so the files that are being installed in the ntsc and pal folders are different to what i sent you

i just redownloaded the .zip file i sent you and overwrite the files and it fixes it.

**Comment by Rocky5** [comment]
> okay, somethings not right. I do a force update and the left hand menu is off alignment on y axis by about 60 and the update page is out of alignment. The _Script_URLDownloader.xml in the ntsc folder of the simple theme is showing 1280x720. so the files that are being installed in the ntsc and pal folders are different to what i sent you
> 
> i just redownloaded the .zip file i sent you and overwrite the files and it fixes it.

Yeah you didn’t change the sizes in the header files. I build the “ _Script_URLDownloader.xml” file using those files.

**Comment by loggio** [comment]
ohhh My bad, I misunderstood what the template was for.  I'll fix them up. Cheers.

**Comment by Rocky5** [comment]
> ohhh My bad, I misunderstood what the template was for. I'll fix them up. Cheers.

fixed and uploading

**Comment by loggio** [comment]
> > ohhh My bad, I misunderstood what the template was for. I'll fix them up. Cheers.
> 
> fixed and uploading

you're too quick! Thank you.

**Comment by Rocky5** [comment]
> > > ohhh My bad, I misunderstood what the template was for. I'll fix them up. Cheers.
> > 
> > 
> > fixed and uploading
> 
> you're too quick! Thank you.

Nah thank you, for doing the legwork.
