### ISSUE TITLE
Missing text on screen for some menus

### ISSUE THREAD

**Issue by lordtaki** [Rocky5/XBMC-Emustation#102]
Hello,
even with a fresh install of the last build, most of the text in menu or options are missing.
For example, when pressing the start button, the menu pops up without any text.
When selecting 'Options' some entries are missing (after and before "System Information").
Thank you for your help.

**Comment by Rocky5** [comment]
That’s a new one, can you enable debugging mode (hold X+Y when loading emustation & send me the log file from Q:\system\ please. 

Also what resolution are you running in? and are you using a CRT, or composite cables?

**Comment by lordtaki** [comment]
Hello, will let you know this evening back home.
I use a component cable -> OSSC -> A/V receiver -> OLED TV.

**Comment by Rocky5** [comment]
> Hello, will let you know this evening back home. I use a component cable -> OSSC -> A/V receiver -> OLED TV.

Then they should be showing. If you’re using FileZilla to transfer over the files, make sure the transfer mode is set to binary. 

Alternatively just update to stable in the downloader to bypass ftp issues.

**Comment by lordtaki** [comment]
Thank you for the advice for FileZilla. I will double check it. I totally restarted from scratch I'm not sure if I can reach again easily the downloader.
If it persists I will take some pictures.

**Comment by Rocky5** [comment]
> Thank you for the advice for FileZilla. I will double check it. I totally restarted from scratch I'm not sure if I can reach again easily the downloader. If it persists I will take some pictures.

As long as you have your Xbox plugged into a router/modem you can use the downloader to update to the stable build. 
(it’s under the options menu)

**Comment by lordtaki** [comment]
Hi again. Forcing binary mode in FileZilla solved the issue. Thank you for the support.

**Comment by Rocky5** [comment]
> Hi again. Forcing binary mode in FileZilla solved the issue. Thank you for the support.

🙏 no problem 😁
