### ISSUE TITLE
Nkpatcher flicker filter bug

### ISSUE THREAD

**Issue by benjis8888** [Rocky5/XBMC-Emustation#103]
Where can I report an issue with nkpatcher from Rocky5 softmod? It doesn't have an issues tab

The flicker filter OFF setting in nkpatcher does not work. After setting it to OFF and power cycling the console, flicker filter is not off, it certainly is not off when you run a an xiso with the attacher or from an actual disc, the flicker filter is well and truly on. If you set it to OFF then it should be off when running xisos and discs shouldn't it? Tested on 3 different consoles in 480i wide-screen mode, same results so it's not working and not applying the flicker filter patch properly 

Another issue I want to report is with chimp, it will not clone F or G and stops every time after E and I've tried most of the partition options. Also same goes for creating partitions on the slave in advanced and selecting all the options,  F takes 137gb, rest on G etc. and it always does a partition of F and G getting equal space and ignores your selection

**Comment by Rocky5** [comment]
For a start the right GitHub repository would be a start. “The Xbox softmodding tool” this one if for a dashboard. 

But flicker filter I only doing out doesn’t work a couple month ago. I will take a look, but there will be broadly no fix, unless someone else wants to try fixing it. (I can’t test it properly as I can only use HDMI and there is no difference when viewing it)

As for chimp, you use X on the controller to select stuff and A to proceed through the menus. (Common mistake is using A thinking you’re picking an option, you’re not)

But you will need a partition table for it to clone partitions, that’s why “XBPTable Writer” was made. Run it, use the correct option that matches your master drive.
