### ISSUE TITLE
Cant see ports tab in emustation

### ISSUE THREAD

**Issue by wooliegun** [Rocky5/XBMC-Emustation#104]
Hi Ive recently installed the latest version of xmbc-eumstation. after installing I downloaded the doom port but when prompted during the process to select a folder could not see a port folder in the roms folder in my [F] partition. Ive tried adding my own one and also tried adding one on my [E] partition but still no luck. when I refresh the carousel nothing appears. Any help would be appreciated :) thanks!

**Comment by Rocky5** [comment]
E,F or G:\Ports\

It’s setup that way so other dashboards can use the same content. Only emulators and roms for this systems go in the roms folder for emustation.
