### ISSUE TITLE
How to have Game and Watch emulation working on a softmodded xbox?

### ISSUE THREAD

**Issue by JFGo1974** [Rocky5/XBMC-Emustation#105]
Hi,
I have a full Game and Watch 0.254 romset that I would like to see running on my softmodded XBOX using XBMC-Emustation MAME...
Is this possible and how?
Thank you
JFGo

**Comment by Rocky5** [comment]
Mame on Xbox requires a very specific set of roms, so probably not. 

Xbox emulations for arcade is limited unfortunately.
