### ISSUE TITLE
Black screen upon launch...

### ISSUE THREAD

**Issue by BoomerangBandit** [Rocky5/XBMC-Emustation#106]
xbmc 3.5 latest build from website. 720p

**Comment by Rocky5** [comment]
Download the prebuilt version and don't build the source.

There is a download link in the readme.md file.

**Comment by BoomerangBandit** [comment]
link in readme lands on blank white page :)

**Comment by Rocky5** [comment]
> link in readme lands on blank white page :)

link is readme.md works fine, Its a google drive linke.
https://drive.google.com/file/d/1SH84C_T7n59fy0pcz2ji5ouA2NYKRSgR/view
