### ISSUE TITLE
Ability to filter for Xbox game attributes (4 player, kids, DDR Pad, etc.) (***Enhancement***)

### ISSUE THREAD

**Issue by ZacharyLeahan** [Rocky5/XBMC-Emustation#108]
At the XBOX game selection screen, it would be great if there was an ability to filter by attributes.

Example Filters:
Number of Players: Single-player, Multiplayer (local or online), Co-op, Split-screen
ESRB Rating: E (Everyone), E10+ (Everyone 10 and up), T (Teen), M (Mature)
Genre: Action, Adventure, Racing, Puzzle, Sports, RPG, Shooter, Fighting, Platformer, Simulation, Strategy
Peripheral Support: DDR Pad, Light Gun, Steering Wheel, Xbox Live headset
Game Mode: Campaign, Versus, Free-roam, Online Multiplayer, Party Mode
Developer/Publisher: Popular studios or publishers, e.g., Microsoft, Ubisoft, EA
Xbox Live Support: Yes/No, Online Multiplayer, DLC availability
Exclusive: Xbox Exclusive, Console Exclusive, Cross-Platform
Graphics Style: Realistic, Cartoony, Cel-shaded
Series/Franchise: Part of a franchise or a standalone title
Release Year: Filter by year or range (e.g., 2001–2006 for Xbox)

If we had the data, how hard would it be to update the UI?

**Comment by Rocky5** [comment]
First this isn’t an issue so please don’t abuse this section for stuff that isn’t broken. 

The data would need to be stored somewhere & then pulled and processed. The programs menu doesn’t do that like the movies library mode does etc… as it’s barebones. I would need to move programs over to how movies are done and that’s an undertaking I don’t want to do. (It’s not a simple task)

I may see at some point not any time soon if I can jerry rig so to speak a way to sort by different criteria’s but it won’t be all the ones you listed. 

It also won’t work like the movies library mode as it can’t.
