### ISSUE TITLE
Black screen when I launch a rom

### ISSUE THREAD

**Issue by Cyprien059** [Rocky5/XBMC-Emustation#109]
Hi Rocky5 thanks for xbmc emustation.
 I install xbmc emustation in the Xbox E partition (application folder).

I can launch without problem xbmc emustation via Dashboard application but when I launch a rom I have a black screen (also when I press the Y button for emulator parameter). I specify that I put the roms in the correct folder....

As if there was no signal on the video input of my TV. I tried on 3 different TV and it's the same problem.

Could you help me?
Thanks

**Comment by Rocky5** [comment]
What resolution are you running at? (480i or 480p and up?)

Also what emulator?

**Comment by Cyprien059** [comment]
Hi
Résolution is 480p

I put rom for nes snes and mastersystem

**Comment by Rocky5** [comment]
Hmm, then should be working. As scanning in roms without an emulators will notify you. 

Once emustation exits (loads a Rom) it’s nowhere emulators that’s in control so there is no way for me to debug that. 

Can you disable widescreen if enabled and 480p please and see if they load?

Even if a Rom is breaking the command line launching (if it sends in ( is does) pressing Y to load the emulators manually should work.

**Comment by Cyprien059** [comment]
I disable widescreen and also 480p
It's always black screen

when i launch manually the emulator (in the carrousel for exemple front of logo nes) i press Y and i have the same thing: black screen with signal lost.

**Comment by Cyprien059** [comment]
I specify that I am making these resolution changes in the Xbox menu (not in emustation program)

**Comment by Rocky5** [comment]
Can you try reinstalling it from scratch elsewhere and only add 1 Rom for SNES (in zip format) scan it in and then try launching the emulator. 

Or navigate to Q:\emustation\emulators\snes\ and run the default.xbe.

**Comment by Cyprien059** [comment]
I reinstall on partition E
Rom Scan it's ok with rom zip format (snes)
But the same problem
When i navigate  in Q:\emustation\emulators\snes\ and run the default.xbe

This file doesnt launch with the same problem
Black screen and no signal 
I restat the console with l+r and button start and black

**Comment by Rocky5** [comment]
> This file doesnt launch with the same problem Black screen and no signal I restat the console with l+r and button start and black

What do you mean doesn’t launch with the same problem? (So it works?)

I don’t really know what to say as you’re the first person to come forward with this issue in all the time emustation has been about. 

Can you run the update option under the update tab in the downloader please? I want to eliminate FTP issues. 

That will install new files, when asked to replace emulators pick yes. Let me know how you get on.

**Comment by Cyprien059** [comment]
Hi John sorry for my late response 
No it's doesnt work 
I reinstall everything again
I update with the downloader
When I run the the file defaut.xbe for exemple in Q:\emustation\emulators\snes\ with file explorer
I have black screen with signal lost

It's stranger because I can launch a cd game without trouble

**Comment by Rocky5** [comment]
i honestly don’t know, you’re the first person that I know of to have this issue. 

Do you have another Xbox you can try?

**Comment by bootsequenc3** [comment]
I ran into same issue, turns out some of the roms do not load for me. ie: genesis emulator loads, lists games, pick the first game 36 great holes. blue dot visual moves along the screen, screen goes black and the system hangs.
hard reboot xbox, load genesis, pick another game, 688 attack sub, loads and plays just fine.

maybe i have a rom name mismatch with the emulator? well, I open the file explorer, run the genesis emulator from the .xbe, browse to the rom that wont load in the emustation gui and it wont load from the emulator either. This confirms the issue is not with emustation, maybe the rom set and emulator need updated? I'll try that.

I'm only adding all this because I hope to save someone else a bunch of head scratching IF they ever come across this
