### ISSUE TITLE
Game Boy bug: loading error, seems to be related with Super Game Boy Enhanced dumps

### ISSUE THREAD

**Issue by evertonstz** [Rocky5/XBMC-Emustation#11]
Hey Rocky5, I've found a strange bug, it seems to be related with roms that are "SGB Enhanced" and how Emustation is passing the loading command to the emulator:

If I load the ROM from Emustation I get this error: https://imgur.com/a/hIz3nee
Of course I did what the error screen said and reescaned the gameboy folder, the error persists.

So I went to the File Explorer and opened the default.xbe at .emustation/emulators/gb/default.xbe and loaded the ROM from the emulator interface, the ROM loaded fine: https://imgur.com/a/rM3wIej

ROM used in the pics: _Donkey Kong Land (USA, Europe) (SGB Enhanced).zip_ (filetype inside the zip is also .gb like the vanilla roms)

Other games that I tested and got the same error:

- Donkey Kong Land 2 (USA, Europe) (SGB Enhanced).zip
- Donkey Kong Land III (USA, Europe) (Rev A) (SGB Enhanced).zip
- Castlevania Legends (USA, Europe) (SGB Enhanced).zip

Vanilla Game Boy games seems to be working fine, even tho I didn't do extended testing. Does emustation log this type of action anywere? If yes I can dump this log and provide it here.

**Comment by Rocky5** [comment]
Can you send me your gamelist\gb folder please. 

And the Q:\system\xbmc.log file after you get the rescan rom message. 

It’s probably a naming issues with all the () characters in the name.

**Comment by evertonstz** [comment]
The xbmc.log is here: https://pastebin.com/raw/rtYhHCk8

for the gamelist folder:
favslist.xml: https://pastebin.com/raw/CcdPVB11
gamelist.xml: https://pastebin.com/raw/4YZSZPRe
jumplist.xml: https://pastebin.com/raw/xGfJm1h4

BTW: I use No-Intro naming scheme, so all my roms have () in the name, for exemple: Casper (USA).zip launches fine.

**Comment by Rocky5** [comment]
Leave it with me and I will send you an updated launcher.py file to test out.

**Comment by Rocky5** [comment]
Also remember there is a filename character limit of 42 characters including the extension. This is due to the FatX filesystem.

so Donkey Kong Land 2 (USA, Europe) (SGB Enhanced).zip becomes Donkey Kong Land 2 (USA, Europe) (SGB.zip

**Comment by Rocky5** [comment]
Here you go this will fix your issue. I will redo this script at a later date.
https://pastebin.com/1AkZnDMw
(its just a quick hack fix)
