### ISSUE TITLE
PSX CHD and M3U

### ISSUE THREAD

**Issue by nogarth** [Rocky5/XBMC-Emustation#110]
With the PSX emulator now able to use CHD can Emustation for XBMC use the m3u file for if it is multi disc game. Which is how we do it in Batocera and would help solving the issue with Multidisc games as i cant find the solution for the multi disc with CUE files.

**Comment by Rocky5** [comment]
A would need to add that to it, leave it with me and when I get time I will.

**Comment by nogarth** [comment]
example of the m3u content.

Wing Commander IV - The Price of Freedom (Disc 1).chd 
Wing Commander IV - The Price of Freedom (Disc 2).chd 
Wing Commander IV - The Price of Freedom (Disc 3).chd 
Wing Commander IV - The Price of Freedom (Disc 4).chd

**Comment by Rocky5** [comment]
> example of the m3u content.
> 
> Wing Commander IV - The Price of Freedom (Disc 1).chd Wing Commander IV - The Price of Freedom (Disc 2).chd Wing Commander IV - The Price of Freedom (Disc 3).chd Wing Commander IV - The Price of Freedom (Disc 4).chd

Does the emulator support m3u files? If not then those will be useless unless.

As you can just amend chd files with the disc number, in fact the same can be done with cue files.

**Comment by nogarth** [comment]
i'll check as have a feeling they dont but the PC version does i'll look and test more.

**Comment by Rocky5** [comment]
> i'll check as have a feeling they dont but the PC version does i'll look and test more.

Yeah this isn’t really emulationstation, but a recreation using XBMC4Xbox source edits and python to mimic the look, feel and options of the PC version. 

Some are limited to really old emulators and none of the advanced or normal stuff we are accustomed to now a days.

**Comment by Rocky5** [comment]
I just checked and the emulators doesn't work with m3u files. So the file names will need to be changed to reflect discs.
