### ISSUE TITLE
Sega CD CHD not scanning

### ISSUE THREAD

**Issue by nogarth** [Rocky5/XBMC-Emustation#111]
With Sega CD now able to use CHD files it you have it in the root of roms/segacd the games are not picked up. 
Even testing having it in a Subfolder does not work.

its looks like the scanner does not have this functionality to pick up CHD filetype for Sega CD latest build.

**Comment by Rocky5** [comment]
A will check this out.

**Comment by nogarth** [comment]
ok update and litte work with Rocky5 it ended up being that the Sega CD scan options was set to ON which only searches for ISO,CUE etc toggle to OFF to correct that issue.
