### ISSUE TITLE
FTP full access

### ISSUE THREAD

**Issue by nogarth** [Rocky5/XBMC-Emustation#112]
Can it be looked into for the FTP user permissions be the same as the way unleashX as that seems to be a Root level FTP account as i had issues removing files that said didnt exists or access denyed and had to with to UnleashX to remove this.

Be nice to have it all under one roof.

**Comment by Rocky5** [comment]
That’s just a quirk of XBMC, some things get write protected and you need to use UnleashX to remove them. 

So I may look into it at some point but it’s not something that is urgent.
