### ISSUE TITLE
synopsis python script

### ISSUE THREAD

**Issue by nogarth** [Rocky5/XBMC-Emustation#113]
When running the script with a gamelist.xml error occurs
 
![image](https://github.com/user-attachments/assets/1808431d-d10b-42f6-9fd4-3a18a814e71e)

not an expert but is this something to do with what python version is running

my installed verion python 3.12

**Comment by Rocky5** [comment]
Requires python 2.7. Install that and it will work.

**Comment by nogarth** [comment]
yup that fixed the issue for this.
