### ISSUE TITLE
Halo 2 dlc not working xbmc emu station downloader

### ISSUE THREAD

**Issue by iMoWgLii** [Rocky5/XBMC-Emustation#114]
I downloaded the halo 2 map pack using the downloader on the Xbmc emustation dashboard. All the maps work except tombstone. It loads after the count down then goes to black screen then back to the lobby. I can’t play any of the playlist because I’m missing tombstone.

**Comment by Rocky5** [comment]
This isn't an emustation problem, but I reuploaded the file. Seems mine was to small so something must have been corrupt.

**Comment by Rocky5** [comment]
Just want to update, installed and all working.
