### ISSUE TITLE
Pressing the "start sreensaver" (select) key when the screensaver is disabled will result in a black screen you can't get out without reset

### ISSUE THREAD

**Issue by evertonstz** [Rocky5/XBMC-Emustation#12]
Nothing is logged at "xbmc.log". I'm having this problem for some time, forget to report it. Here's how to reproduce:

- turn off the screensaver at settings, reset the console
- wait around 10 minutes and press select to manually activate the screensaver
- the screen will turn black and you'll be locked there even tho you can still hear the sound effects from the UI if you press left or right, only way out is a restart

I'll reactivate the screensaver to see if I can reproduce the error with it on.

EDIT: after some testing the bug seems to occur only with the screensaver off

**Comment by Rocky5** [comment]
Fixed this in the hotfix, you can exit back out of the window if no screen saver is set. (There is no way to determin if it’s not set so, but leave it with me and I will see if I can find a workaround)
