### ISSUE TITLE
"Apply flicker filter setting to games" doesn't work + default.py from "480p Game Loader.zip" gives a module error

### ISSUE THREAD

**Issue by evertonstz** [Rocky5/XBMC-Emustation#14]
The option is on "Programs > General > Apply flicker filter setting to games", I guess it's an built version of your script to fix the flickering for some games in the 1.6 Xbox, right? I did set it to "ON", did a lib rescan and restarted the system, the flickering games still flickering (tested with Gunvalkyrie, JSRF and Panzer Dragoon Orta.

The other bug is from your old "[480p Game Loader.zip](https://drive.google.com/file/d/0BzRN8P835YijNkVEdUlFSUFMUzQ/view)" file, I extracted the script folder and merged with the current one I have in the xbox, resulted in two new folders: "scripts/480 Game Loaders" and "scripts/.modules". I try to launch the default.py, but I get the following error: "Module is missing: script.module.limpp".

The limpp seems to fine inside "scripts/.modules/script.module.limpp", and I even tried to move the "scrits/.modules" folder to "scripts/480 Game Loaders/.modules" but the result error is the same.

**Comment by Rocky5** [comment]
Flicker filter you press white on on a game and launch it I think, it’s a built in feature of XBMC. (The source code for this hasn’t been altered by me, so if it doesn’t work it won’t work in XBMC3.5.3)

You can use FlickerFucker to manually patch these games. 

Use XBMC4Gamers for the 480p patching, currently can’t look at why it’s not working so you will be quicker just running XBMC4Gamers.

**Comment by Rocky5** [comment]
You will need to patch the games xbe manually, as it will patch the loader instead of the actual game xbe, if you ran the 480p game loader on those games. (It patches default.xbe)

**Comment by evertonstz** [comment]
Yep, got it done with xbmc4gamers! Thanks for the info, Rocky5, I was not aware it had those scripts built in.
