### ISSUE TITLE
Not so much an issue more a question

### ISSUE THREAD

**Issue by steverae68** [Rocky5/XBMC-Emustation#15]
Keep it simple, tried this on my JTAG 360 under the original xbox emulator and it failed miserably.  Are their any plans to make this work on such a system ?

**Comment by Rocky5** [comment]
No, it’s for the original Xbox only. The 360 Xbox emulation isn’t opensource so no one can make stuff compatible. 

I also won’t be porting it to the 360 version of XBMC, just to much work involved.
