### ISSUE TITLE
Games Artwork Dowload 1.7 hangs console.

### ISSUE THREAD

**Issue by Haker120** [Rocky5/XBMC-Emustation#18]
Console is 1.6, XBMC4Games is the newest 1.2.122, when console tries to install it, it doesn't hang right away at extracting screen, not always, but when I'll hit B it does. Cache was formatted, even entire HDD was formatted and nothing changes, it downloads installer just fine but doesn't unpack at all and hangs.

**Comment by Rocky5** [comment]
Disable 1080i and only use 720p or lower for my dashboards. 1080i eats up to much ram on stock consoles.

**Comment by Haker120** [comment]
Alright, thanks for quick answer, and does matter if it's actually turned off or changing to 720p 16:9 is enough?

**Comment by Rocky5** [comment]
If you have 1080i enabled in the system settings menu, just disable it and press B to back out to the main settings window (where the downloader button eg... is)  Pythia makes sure the setting is saved. (XBMC saves settings on exiting a window, so not to corrupt GUIsettings.xml)

Restart and you should be good, I recommend 720p max for OGXbox as the 1080i it to demanding on it for what little power and resources it has.

**Comment by Haker120** [comment]
Thanks, that explains no issue on my other 1.4 with 128MB RAM. It's around 500MB but download is so slow. :D And I just turned off 1080i to not have any more problems. ;)

**Comment by Rocky5** [comment]
Let me know how you get on, and I know it’s slow but it’s unlimited bandwidth and 100GB of storage, so can’t really complain.

**Comment by Haker120** [comment]
I will but it'll take some time. :)

**Comment by Haker120** [comment]
Ok, I'm happy to report with 720p 16:9 resolution Games Artwork Dowload 1.7 downloaded and installed itself successfully. :)
