### ISSUE TITLE
Issues with PSX CUT file creation

### ISSUE THREAD

**Issue by TelaKeppi** [Rocky5/XBMC-Emustation#2]
I saw you updated the code and decided to try new version. There's still some issues. Maybe I didn't explain it clearly, but automatic CUT file creation still makes CUT files for other than .CUE files for PSX. For example 20 .CUT files for Destruction Derby, since the game has 20 tracks on the original CD. Yes it's technically possible to launch a PSX game straight from the .BIN file, but you get a error message from PCSXBOX and loose all audio tracks.

Another thing, if you manually delete .CUT files and refresh .CUT files from the menu, only game/rom count get's updated, the actual game/rom list is not updated.

**Comment by Rocky5** [comment]
There are 20 cut files for one game?

Send me the game please, and if its the case then not sure what I can do for parsing 30 cut files, why is there not just one cut file for the game with all the offsets in it?

**Comment by TelaKeppi** [comment]
Sure I can send it to you, but it's the same issue with all multi track games, for Alien Resurrection I have files,
02.08.2017  16.53      270 035 472 Alien Resurrection T1.bin
02.08.2017  16.53        15 292 704 Alien Resurrection T2.bin
02.08.2017  16.53        18 545 520 Alien Resurrection T3.bin
02.08.2017  16.53        32 104 800 Alien Resurrection T4.bin
02.08.2017  16.54               402 Alien Resurrection.cue

And as a result of creating the cut files, I get 4.

**Comment by Rocky5** [comment]
Yeah I just downloaded it and can see that, will see what I can do.

**Comment by TelaKeppi** [comment]
I'd just filter out all but .cue files for creating .cut files for psx games.

**Comment by Rocky5** [comment]
OK the one I downloaded for DD is .img and .cue file and Im guessing you have the .bin version?

**Comment by TelaKeppi** [comment]
Yes, all my games are currently .bin/.cue versions. Oh I see, .bin files are separate tracks while .img files are the the whole image with offsets in cue file.

**Comment by Rocky5** [comment]
can you send me the link to the multi file one please?

**Comment by TelaKeppi** [comment]
Well I wouldn't like to directly link it here, but it's the one in Emuparadise, "Destruction Derby [U] (500M)"

**Comment by Rocky5** [comment]
I added .ccd support to the script so when I commit that if I cant get the cue files to work you can use ccd files.

**Comment by TelaKeppi** [comment]
I've manually created .cut files from .cue files an they definitely work. But the script would have to filter then for both ccd and cue files to get it working automatically.

**Comment by Rocky5** [comment]
Yeah it works for ccd but will test the version if DD you have and get back to you.

**Comment by Rocky5** [comment]
edit the create_cut_files.py and search for:
else:
	Write_CUT_File = 1

and change the 1 to 0 and scan the PSX directory again.

**Comment by TelaKeppi** [comment]
Ok, that did the trick. The were 2 instances, edited them both.

**Comment by TelaKeppi** [comment]
Actually, now it completely skipped creating cut files for multi track games, but now the list is way cleaner. Hopefully you can fix it for good. Now I can manually create the .cut files and rescanning the folder wont mess it up again.

**Comment by Rocky5** [comment]
It will only scan cue files that match the name of a bin file.

example.
works
test.bin
test.cue

wont work
test1.bin
test.cue

changing the 1 to a 0 just skips anything that isn't .cue but it has to have a file that matches.

**Comment by TelaKeppi** [comment]
Oh right, so for the time being, I could just edit the name of the first track to match the cue and then edit the cue.

**Comment by Rocky5** [comment]
Correct

**Comment by Rocky5** [comment]
Correct

I have the script now only parsing .ccd and .cue files. So will do some more testing and then commit the changes for you to test.

**Comment by Rocky5** [comment]
Scripts added test away.

**Comment by TelaKeppi** [comment]
Ok, I can confirm its working now with BIN/CUE files.

**Comment by Rocky5** [comment]
yeah it will only process ccd and cue files.

**Comment by TelaKeppi** [comment]
There might still be other issues with the cut file creation. Im trying to create cut files for Atari Jaguar and both automatic and manual mode does nothing.

**Comment by Rocky5** [comment]
List the systems that use cue or ccd files and I will update the script to work with them.

**Comment by TelaKeppi** [comment]
Virtual JaguarX still has no CD support, so its some other problem with the script.

3DO uses cd based media, but the emulator only loads .img or .bin files. Neo Geo CD uses .cue files. Sega Saturn emulator Yabause uses cue and ccd files. Sega CD emulator uses .cue files. I've yet to try WinUAEX (Amiga) emulator, but it should support CD32 games which are also in bin/cue format.

**Comment by Rocky5** [comment]
updated the script to work with some of those emulators.

segacd, saturn and neo-geo cd. winuaex I have never heard of nor have the emulator for it.

**Comment by Rocky5** [comment]
I fixed the script again, named the neogeocd properly.

**Comment by TelaKeppi** [comment]
Add .j64 to the Extensions list to get Virtual JaguarX .cut file creation to work. Also, the rom files for this emulator have to be in XBMX-Emustation\_emulators\atarijaguar\roms folder or the emulator itself wont work. Direct launching the rom is not working on this emulator, but at least the emulator is till worked on so it might get fixed i'll drop him a bug report.

**Comment by Rocky5** [comment]
I will check that out, it could be the same as FBL and name where the roms must be in the root directory of the emulator. 

Thank you for testing these.

**Comment by Rocky5** [comment]
Committed, but like above its useless.

**Comment by TelaKeppi** [comment]
Yeah, you can close this. Too bad for the emulators that don't support cut files. As a workaround would it be possible launch the emulator straight from the carousel?

**Comment by Rocky5** [comment]
Added that just now, so Atari Jaguar will only be direct launch.
