### ISSUE TITLE
New to emustation and can't scan ROMs.

### ISSUE THREAD

**Issue by sirbacharach** [Rocky5/XBMC-Emustation#20]
Hi,
I'm wondering if my directories are set up wrong.
Some of my platforms contain over 4096 roms, which the Xbox for system seems to be capped at, so I've got zx spectrum for example with sub folders 0-Z, is this the reason I get an error when scanning? I moved all platforms into alphabetically organised folders, is this causing problems with the scan? Shall I just put them back and keep numbers under 4096?

I think it's the spectrum I had the problem with as there are so many files.

Rob.

**Comment by sirbacharach** [comment]
Hi, after more tinkering, I found that it was because I had sub directories within the console, I had the games all alphabetised so I could avoid the 4096 file limit on the xbox file system. Some platforms such as the speccy have well over the 4096 file limit so I alphabetised them. Is there any way around this with your scraper script or can the script be modified to accept the alphabetised folder structure?

I'd do it myself, but I have no idea how to script, I've had a look and it looks very alien to me. :S

Thanks.

Rob.

**Comment by Rocky5** [comment]
Currently no, I may look into adding sub folder support at some point but as of right now I'm currently busy doing some minor changes to emustation and preparing for twins coming. ( so time is scares for xbox stuff now a days )

**Comment by sirbacharach** [comment]
Ah I see. Do you know if there are other compatible scrapers that others may have done for emustation or a site with them on I could maybe browse through?

I want to keep this front end as it's the most aesthetically pleasing.

Good luck with the twin preperation, I think I'd struggle with just the one. :S
