### ISSUE TITLE
Can’t find emulators

### ISSUE THREAD

**Issue by fizdog** [Rocky5/XBMC-Emustation#21]
I see there some emulators installed already through the file system or am I wrong? They won’t show up on the home screen. I installed the n64 one and it doesn’t show up. Not sure if it’s because I have to have it In the F folder. Please help

**Comment by Rocky5** [comment]
This is not an issue, you need to download emulators from the downloader or add your own. There are 20 or 21 emulators included for the most popular emulators but that's all.

You can see what ones are present by looking in here.
https://github.com/Rocky5/XBMC-Emustation/tree/master/Emu%20xbe%20files

**Comment by sirbacharach** [comment]
This comment was not mine, it was someone else's. It doesn't relate to my issue. Can this be re opened?

**Comment by fizdog** [comment]
Wether it’s an issue or not I’ve downloaded a n64 emulators right off the download section and it didn’t show up. I see there also is a snes emulator as I played a game with it. Still doesn’t show up and only way I can play it is if I go through the file manager

**Comment by Rocky5** [comment]
You need to have roms in the folder ".emustation\roms\n64" for example and then scan them in. If you do not, then nothing will show as its not a bug but intended behaviour.
( if no roms hide carousel entry)

**Comment by fizdog** [comment]
Ok gotcha. Thanks will give it a try

**Comment by fizdog** [comment]
Actually I should have mentioned I did have a snes game and it still doesn’t show up

**Comment by Rocky5** [comment]
Can you show me your folder structure, the folder with snes games in it and if using custom paths for the three folders the other settings menu please.

**Comment by madforroms** [comment]
Good day Rocky , I have DL N64 emulator  from inside EmulationStation but I get a script error trying to update N64. Alternative it will call out earthroom Jim emulator missing ? Can you please help me?

**Comment by TRex2020** [comment]
Hi Rocky5, 
I am using your XBmc emustation on my XBox 1.2 and try to configure the SNES  emu. Is it possible to do this about XBmc emustation?  

If I start a rom over the SNES emu the game is only displayed in the middle of my widescreen TV with 1/3 screensize. If I use my original SNEs the game screen is displayed over the whole display screen of my TV.

Can I change that in emustation?

**Comment by Rocky5** [comment]
Press Y when on the carousel and edit the default options for the emu. (This will make all new games use those settings)

You can make sure it’s enabled by going to Emulators\snes\saves\snes9 or what ever the folder is\ and there should be three default files, if not in the emu settings disable and enable use default configs for all. (Can’t remember the exact name sorry)

**Comment by Shandy1982** [comment]
Rocky, could I ask for some help using your xboxhdm USB tool? I've got a softmodded xbox, and a 2tb image on a drive. I want to clone the drive and drop into the softmodded xbox, is it just a case of nulling hdd key in softmodded xbox, nulling on new drive, locking drive using xboxhdm and dropping it into the xbox?

**Comment by Hamak72** [comment]
Can these PSX SLUS Database files be of help to any programmer?

[PSX_SLUS_NTSC_U.txt](https://github.com/Rocky5/XBMC-Emustation/files/4705227/PSX_SLUS_NTSC_U.txt)
[PSX_SLUS_PAL.txt](https://github.com/Rocky5/XBMC-Emustation/files/4705228/PSX_SLUS_PAL.txt)
[PSX_SLUS_NTSC_J.txt](https://github.com/Rocky5/XBMC-Emustation/files/4705229/PSX_SLUS_NTSC_J.txt)
