### ISSUE TITLE
Emustation not booting into 480i w/ component cable NTSC-US

### ISSUE THREAD

**Issue by Midian-AD** [Rocky5/XBMC-Emustation#22]
Hello,

I'd like to use emulationstation dashboard with an old Sony Trinitron CRT Style TV. I have realized that emu station wants to boot into 480p which gives me a picture of digital garbage. Is there any way to boot into 480i? For example unleashx X dashboard you can hold the back button when you turn the console on and it boots to 480i with the component cables. I appreciate your help and if it hasn't been implemented it might be a decent option in future builds.

Thank you for your time

**Comment by Rocky5** [comment]
I will take a look in the source, but your best bet is to just disable 480p in the settings menu before running it on the CRT.

**Comment by Midian-AD** [comment]
That resolved it but you have to connect it to a HD TV  to do it and not a CRT with component.  Thanks.
