### ISSUE TITLE
URLDownloader not working.

### ISSUE THREAD

**Issue by loggio** [Rocky5/XBMC-Emustation#23]
Hi there,

It appears the URLDownloader is no longer working on either of my XBOX's 
When i select something to download, it will just sit there trying to load and nothing happens.

Can you confirm if there is an issue with the server?

**Comment by Midian-AD** [comment]
I just used it 10 mins ago from this message to add a few things to a new
softmodded system. No issues for me.

R. "Midian" Muir

**Comment by loggio** [comment]
Yes, you're right very strange that both machines are having the same problem, but it looks like my emustation has become corrupt. I've reinstalled from the softmod extras disc and it's working fine again... 

I'll just have to re download everything fresh.

Thanks.
