### ISSUE TITLE
Gameboy Gamelist Issue

### ISSUE THREAD

**Issue by hgoda90** [Rocky5/XBMC-Emustation#24]
When the gamelist is created for Gameboy games the gamelist is missing the last character of the game title. I fixed the issue temporarily by creating a space at the end of the rom file.

**Comment by Rocky5** [comment]
I take it your rom extensions are only 2 characters long? will take a look at the script to see how I truncates the extensions.

But I recommend zips for all roms, you won’t notice a difference but it saves space.

**Comment by hgoda90** [comment]
The Gameboy roms are in the .gb extension but if .zip would work better than I would just zip them all.

**Comment by Rocky5** [comment]
Yeah I just truncate a file instead of extracting the extension, will fix it for the next release.
