### ISSUE TITLE
Emulators/Roms...ISSUE...OOPS?

### ISSUE THREAD

**Issue by angus31** [Rocky5/XBMC-Emustation#25]
Hello!

SO I THINK I got everything setup correctly.  However, a couple things I've noticed (Fyi - I've been using Modern Vintage Gamers video as a reference).  SO when I get to the screen that has XMBC Options, Ports, and games I think?  Two things - First, when I hit Y to bring up the menu for other options to scan I believe?  It just says OOPS, You can only do that in an emulator or something like that.  The other thing I noticed - is on the video, on the bottom left there is a key A-Select, X-Random, > Menu etc.  My screen does NOT have those icons in the bottom left.  Not sure if that is relevant or not.  Also - I did FTP a few roms of several different systems into each ROM folder as well.  But as mentioned above - I can't get any emulators to come up or even scan.  Please help!  Thanks

**Comment by Rocky5** [comment]
Hi, you press start when on the carousel and select other options > Auto Scan. To scan stuff. 

As for the icons, head to Options > calibrate screen, now when you see the big square in the center of the screen use A to cycle through the movable points. (Adjust the corners to match your screens overscan)

**Comment by angus31** [comment]
Hello

So that’s the thing.  I’ve pressed start (and every button). Nothing/no menu comes up.  The ONLY thing that ever comes up is when I hit Y and a box comes up that says oops, you can only do that in emulators etc.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Rocky5** [comment]
If pressing Y brings up the direct launch emulator dialog, then the control config file is intact. Make sure XBMC-Emustation is installed properly, as pressing the start button while on the carousel (where you select a system) brings up a dialog menu with more options.
