### ISSUE TITLE
No 6 button mode

### ISSUE THREAD

**Issue by BigJon20** [Rocky5/XBMC-Emustation#26]
Hello Rocky5 I have just downloaded and installed Emustation 1.2.123. When I go to play my genesis games there’s no option for a 6 button controller and I’m stuck at the 3 button configuration. I’ve looked everywhere I could think of for an option to change it but didn’t see it. Is there a fix for this or am I missing something within the emulator. Thanks

**Comment by Rocky5** [comment]
Press Y on the genesis icon on the carousel. 

Edit the default settings for all games option (above settings) enable 6 button pad option. 

Note some games don’t work and you won’t be able to control them when 6 button is enabled.

**Comment by BigJon20** [comment]
Thanks for the fast reply, I was able to change it but it still wouldn’t allow me to play in 6 button mode. The game in particular is Wrestlemania Arcade which supports the 6 button controller. I also tried switching the emulator core to neogenesis but it yielded the same results.

**Comment by Rocky5** [comment]
You would need to edit that specific games config or just remove it from the saves folder of the emulator. 
(You can navigate to the roms via the rom browser in the emulator and press X or Y to edit it’s config)

**Comment by BigJon20** [comment]
Hey Rocky, just a heads up I was able to solve my issue by putting a different emulator in the emulators folder. Thanks

**Comment by Midian-AD** [comment]
Which emulators did you use to replace them?

R. "Midian" Muir

**Comment by BigJon20** [comment]
The neogenesis emulator by madmab

**Comment by Rocky5** [comment]
Copy the Sega32x emulator and you will have the same emu already setup.
