### ISSUE TITLE
Favorites Not Working, Question About Ports

### ISSUE THREAD

**Issue by Steve007101** [Rocky5/XBMC-Emustation#27]
On the latest stable version. The favorites section does not seem to work, it remains blanks when I add things although the count in the menu is correct. Also, the count for ports reads 0 even when I download additional ports. Is there a default folder it checks for ports in so I could FTP them in?

**Comment by Rocky5** [comment]
Try the test build and get back to me.

Ports you need to update the carousel in the other settings menu.

**Comment by Steve007101** [comment]
Thanks those both work. Is there another forum that's more appropriate to ask non issue related questions?

**Comment by Rocky5** [comment]
Right now I’m a bit busy with new kids and real life so I don’t go on forums much, well not to do with Xbox stuff.

But there is ogxbox forums, folk there can help you out and if I’m on there I can help out also.

Reddit is also good for help regarding my stuff.

**Comment by Rocky5** [comment]
Fixed in the latest test build. 

Ports now require scanning as they can now have synopsis like Xbox games eg...
