### ISSUE TITLE
Surreal 64 from URL Downloader not correct settings

### ISSUE THREAD

**Issue by Steve007101** [Rocky5/XBMC-Emustation#29]
Some games seem to load but some do not, others clearly have broken settings. On the XBMC Emustation beta. Fresh/deleted UDATA/TDATA folder. EWJ 212 roms in emustation roms folder. URL Downloader for the emulator.

**Comment by Rocky5** [comment]
Not an issue at my end. That’s the emulator issue with its command line launching.

**Comment by edg1234** [comment]
Ok.thanks again

**Comment by Rocky5** [comment]
I may have stumbled across something, I had the black screen crap as you did. But I loaded into surreal and set the rom path and let it scan the roms in (surreal keeps a db of the games it finds in TDATA) now 007 eg... load from emustation fine.

**Comment by edg1234** [comment]
Ok awsome. thanks again
