### ISSUE TITLE
Downloader

### ISSUE THREAD

**Issue by Midian-AD** [Rocky5/XBMC-Emustation#30]
After adding some games to the homebrew folder on the hard drive and then I selected to refresh carousel, I ended up getting a "no game lists" error. I was able to rescan everything and everything is fine except I'm no longer able to use the downloader section. It opens up and i can select something to download but I only get the 1-4 blue dots in the upper left repeating as if it is loading, just nothing happens.  Is something going on with the downloader or do you have any suggestions on which files to remove so I can force it to download the downloader again? What do you think?

Thanks in advance,

**Comment by Midian-AD** [comment]
And I believe this may be related but it no longer automatically checking for updates.

**Comment by Rocky5** [comment]
Download the prebuilt version and overwrite the .emustation folder.
Restart and load the downloader.

**Comment by Midian-AD** [comment]
Issue resolved. Thank you very much.
