### ISSUE TITLE
Create_roms_list.py

### ISSUE THREAD

**Issue by wskclown** [Rocky5/XBMC-Emustation#32]
So I can't figure out what's going on with this. Is there a way I can manually create roms list. I'm using lastest stable version. Surreal64 .

**Comment by Rocky5** [comment]
You need a specific version of Surreal64 with a specific rom set. 

N64 is bad on Xbox so I only allow the preconfigured version floating about to save folk contacting me asking why it runs like dog sh** lol

201 compilation or something like that is the set you want.

**Comment by wskclown** [comment]
Well I used the URL downloader built-in to it from emustation which I have to say I'm quite impressed with what you have done. Other then that with N64. I'm beginning to think you should make your own N64 emulator for Xbox. Your stuff works lol. Where would I go to get right version of surreal64? I can compile it I'm sure with one of my 5 pcs

**Comment by deadpahn** [comment]
I'm also having a lot of issues scanning roms. Autoscan breaks at different spots. "Update Scan" breaks at other spots. And sometimes I get "No default.xbe found in this directory" although I am scanning pcengine or something non xbox related. Also, xbox scanning breaks too.

Is there a way to turn on an error log or enable debugging so I can check which line the script fails at?

P.S. Long story short your tools helped me update my harddrive. BIG THANKS.

**Comment by Rocky5** [comment]
When you get a error, grab the log from Q:\system\

Send me it please. 

The no default.xbe is for the emulator. So if you don’t have one installed for that system. It will tell you there is none as there is no point scan roms for a emulator you don’t have. (You would try lunching a rom and nothing then come here saying it doesn’t work)

**Comment by deadpahn** [comment]
I don't seem to have a Q drive nor do I have a system folder in any of the directories root. Is there another place for this?

**Comment by Rocky5** [comment]
> I don't seem to have a Q drive nor do I have a system folder in any of the directories root. Is there another place for this?

If you’re running emustation you will see Q in your FTP application. So when you see the error notification goto your PC and FTP to the Xbox and head to the path specified above. 

Copy the XBMC.log file and send me it. (Don’t paste it here, use pastebin.com)

**Comment by deadpahn** [comment]
Sorry for the late reply, finally got around to debugging this.
https://paste.debian.net/1121068/

Looks like a bug in create_rom_lists.py at line 1166
```
if Manual_Scan == "manual" :
	ManualScan = 1
	Main_Code()
```
