### ISSUE TITLE
Input Lag

### ISSUE THREAD

**Issue by deadpahn** [Rocky5/XBMC-Emustation#33]
I noticed input lag across on the consoles I've tested so far. SNES, GENESIS, and NES. I tried setting the ANALOG BUTTON SENSITIVITY to 1, but that didn't fix it completely. 

I'll do some more tests with another controller and report back if that was the problem.

**Comment by VKHelldog** [comment]
Dude, input lag is most likely from your TV, set it to game mode and turn off power saving and up scaling then try it.

Also Rocky5 built the dash, not the emulators. If they needed improved you'd need to talk to madmab and I'm pretty sure he left this scene ten years ago having pretty will perfected the emulators he worked on.

As for the rest of that, press right stick and change the video size yourself, takes seconds, and please don't open issues unless thet are actual issues. 

Q is a cache. It will show up on ftp if you're xbox has been active and you've been playing games and returned to the dash.

Rocky5 does amazing work for us free. He gives us access to it all at no cost.  We realize the need to have better guides perhaps, however there are very strong communities in Facebook and redit that are very helpful if your new.

Thanks, best regards.

**Comment by Rocky5** [comment]
Above, emulators aren’t my issue, I do the dashboard (launcher) side and the emulators are from emuxtras so madmab and others over there would be better suited to this issue. (But enable game mode on your TV to reduce latency you see or at the very least reduce it or eliminate the TV from the problem)
