### ISSUE TITLE
[Feature request] Auto Stretch Screen?

### ISSUE THREAD

**Issue by deadpahn** [Rocky5/XBMC-Emustation#34]
I'm not sure what the terminology is, but is it possible to accurately sctretch the screen of some consoles to match the screen? I know SNES is natively 7:8 and it might be optimal on modern TVs to keep it like so, however, on my CRT it would be cool to see the screen adjusted like it natively would appear (I dont know the term for this). For now, I will use my hardware and switch back and forth to calibrate the screen size

**Comment by Rocky5** [comment]
Press Y on the system you want to configure. 

It’s on a per system basis you you will need to do it for the ones you want. (I can’t automate it as there are different emulators for some systems and it takes 2 mins to do manually)

When you load the emulator you want to change, head to setting and change the video screen size in the options. (Settings)
