### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by Midian-AD** [Rocky5/XBMC-Emustation#35]
Sorry, I know this isn't really an issue but I exhausted my other attempts over the past month. Has any artwork been compiled for SG1000? Also I'm not able to find and location with pre-compiled artwork for use with other emulators in emustation . Can someone assist? TY

**Comment by VKHelldog** [comment]
> Sorry, I know this isn't really an issue but I exhausted my other attempts over the past month. Has any artwork been compiled for SG1000? Also I'm not able to find and location with pre-compiled artwork for use with other emulators in emustation . Can someone assist? TY

Google search wix rapscallion resserection xtras xbox is the under downloads

**Comment by Midian-AD** [comment]
Thank you
