### ISSUE TITLE
Some kind of loading circle

### ISSUE THREAD

**Issue by 1stian** [Rocky5/XBMC-Emustation#37]
Hello, this is not really an issue.. But it would be nice to have a loading circle of some kind when downloading and extracting using the "Downloader" so I know it's not stuck or anything.

Not sure where else to send inn suggestions at this point. So I ended up here. But this must have been suggested before? Oh well, I did it anyway ;)

But awesome job man! Love it! Currently testing out 1.3.0.63(Well being installed while I am writing this).

Thanks!

Kindly regards Stian T

**Comment by VKHelldog** [comment]
Pretty sure it's coming as beta build has a Google drive downloader which is faster and shows a bar, but I'm sure the creator will answer.

**Comment by 1stian** [comment]
> Pretty sure it's coming as beta build has a Google drive downloader which is faster and shows a bar, but I'm sure the creator will answer.

Well true that, but my internet is damn slow.. But thanks for replying :)

**Comment by Rocky5** [comment]
Yeah took me a bit to get what you were meaning. When it says loading... you’re wanting something to indicate it’s not crashed?

If you press the D-Pad in any direction you will hear a click. (Not crashed) If no sound that’s a crash.

But it won’t hand on the downloader (crash) you would get a script error or a dialog telling you what happened if something did go wrong.
