### ISSUE TITLE
Video previews

### ISSUE THREAD

**Issue by Vinoveg** [Rocky5/XBMC-Emustation#38]
Hi, first of all, thank you very much for this piece of art. It’s more a question than an issue to be honest. Sometimes when Im trying to load video previews with Y, it simply crash and then I need to reset my xbox. Is it because of something related to cache or it’s simply because the videos are too big? Some of my gbc and gba roms wont load either, for example pokemon fire red or pokemon crystal wont start at all. I know it’s probably a problem with the emulator but maybe you know some informations that might help!

Thank you very much sir.

**Comment by Rocky5** [comment]
Send me the xbmc-old.log after it crashes, it’s in the Q:\system folder. 

Videos should be relatively small, 640x480 or under, personally I use the retropie dimensions for videos. 

Pokemon, I need the log after you try to run one. If they are launching and it’s loading the emulator, then that’s not an issue at my end but with your roms. (Once it leaves ES it’s the emulator or user error)

**Comment by Vinoveg** [comment]
Thanks for the quick answer,

This is the video preview crash:
[Video Prev Error.txt](https://github.com/Rocky5/XBMC-Emustation/files/4498049/Video.Prev.Error.txt)

My system doesnt generate a xbmc-old.log, just a xbmc.log so I think I forgot to set this option somewhere but anyways, when it ''crash'' I can still access to the hdd via FTP so I was able to get the log file for the video previews.

 When I try to load pokemon crystal it seems like it load the emulator, try to load the rom (black screen) and then get me back to the menu so i guess it refresh the log so that's why I dont see any error in it.

I'll try different roms and dig a little more on that but I ran out of ideas for the video previews, I compressed them and it doesnt seems to work, my snes videos are bigger in all the ways possible and run perfectly, both .mp4. I dont get it.

Thank you.

**Comment by Rocky5** [comment]
Ok so the issue is your file name for your video file and so assume rom. It’s ending with ( so python doesn’t know what to do with it as it things it’s a open bracket for a function 😂

Update to the test build and you will get a lot of fixes and new features. 

Try scanning in your files again when updated and get back to me. (You will also get xbmc-old.log after the update as it’s added in the test builds)

**Comment by Vinoveg** [comment]
Haha I figured it out right after posting it! (Thats why I deleted the post).
Thank you so much I didn't know about the log file, and I will indeed download the last build!
You're the man.
Much love, stay safe!

**Comment by Rocky5** [comment]
No problem :) keep me informed of how you get on please. And how/if you like the test build.

**Comment by Vinoveg** [comment]
Hi!

First of all, I love the update, the video previews auto-start is neat! Some of the GBA Games I was talking about are working too now! (Not everyone but still).

I still have some difficulty with my videos format, I figured out that reducing the fps of them help a little bit. I tried reducing it to 30fps at first but the videos were running so fast that they weren’t synchronised with the soundtrack anymore so I set them on 50fps, it’s not perfect but overall im satisfied by the result anyways.

Had a little problem with the synopsis maker too (It fail on roms containing commas), not a big deal at all though I fixed it real quick but here’s the log if you are interested :
___________________________________________________________________________________________________

15:07:20 M: 34639872  NOTICE:  Processing: Bug's Life, A
15:07:20 M: 34803712   ERROR: Error Type: <type 'exceptions.IOError'>
15:07:20 M: 34803712   ERROR: Error Contents: [Errno 2] No such file or directory: "F:\\Apps\\Emustation\\emustation\\scripts\\synopsis_maker\\n64\\Bug's Life, A.txt"
15:07:20 M: 34803712   ERROR: Traceback (most recent call last):
                                              File "F:\Apps\Emustation\emustation\scripts\synopsis_maker\default.py", line 122, in <module>
                                                with open ( os.path.join( destination,text_filename + '.txt' ), 'w' ) as output:
                                            IOError: [Errno 2] No such file or directory: "F:\\Apps\\Emustation\\emustation\\scripts\\synopsis_maker\\n64\\Bug's Life, A.txt"

___________________________________________________________________________________________________


So basically, almost everything is running flawlessly! BUT! Now I’m facing a new problem!
Surreal64 is working (when I start it through files manager) but ES failed creating the rom list :

___________________________________________________________________________________________________

15:16:19 M: 33501184  NOTICE: -->Python Initialized<--
15:16:24 M: 30953472   ERROR: Control 10 in window 10101 has been asked to focus, but it can't
15:16:27 M: 30937088 WARNING: msvcrt.dll: dll_fstati64 called, TODO: add 'int64 <-> long' type checking
Previous line repeats 1 times.
15:16:28 M: 31301632 WARNING: Error Type: <type 'exceptions.UnboundLocalError'>
15:16:28 M: 31301632   ERROR: Error Contents: local variable 'N64_Rom_Name' referenced before assignment
15:16:28 M: 31297536   ERROR: Traceback (most recent call last):
                                              File "Q:\emustation\scripts\create_rom_lists.py", line 1448, in <module>
                                                Main_Code()
                                              File "Q:\emustation\scripts\create_rom_lists.py", line 1167, in Main_Code
                                                pDialog.update((CountList * 100) / len(os.listdir(Roms_Folder)),'Creating [B][UPPERCASE]'+Emu_Name+'[/UPPERCASE][/B] Rom list and copying media files',N64_Rom_Name,'This can take some time, please be patient.')
                                            UnboundLocalError: local variable 'N64_Rom_Name' referenced before assignment

____________________________________________________________________________________________________

I’m a bit stuck right now, maybe you can help me again with this one!
Thank you!


De : John<mailto:notifications@github.com>
Envoyé le :April 18, 2020 8:21 PM
À : Rocky5/XBMC-Emustation<mailto:XBMC-Emustation@noreply.github.com>
Cc : Vinoveg<mailto:vincent.viger@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [Rocky5/XBMC-Emustation] Video previews (#38)


No problem :) keep me informed of how you get on please. And how/if you like the test build.

**Comment by Rocky5** [comment]
Cheers for the logs, surreal you need a specific compilation Earthwormjames 212 set as N64 isn’t good on Xbox and requires a lot of user testing to get the best settings and cores. So I only allow the former as I was fed up of issues with this emu. 

So get that emu set, download the emu from the downloader and run the scanner. 

As for the synopsis script, I will take a look, it maybe as simple as changing " to ‘ in the script, but I will take a look when I can.

**Comment by Vinoveg** [comment]
Done! The pack is hard to find but it works! I hope I don’t bother you too much with all my questions..

I downloaded xbox artwork installer and ran the .xbe. Did his job, got all the images but no videos and no synopsis. Is it normal?

Thank you very much.

Le 20 avr. 2020 à 16:06, John <notifications@github.com> a écrit :

﻿

Cheers for the logs, surreal you need a specific compilation Earthwormjames 212 set as N64 isn’t good on Xbox and requires a lot of user testing to get the best settings and cores. So I only allow the former as I was fed up of issues with this emu.

So get that emu set, download the emu from the downloader and run the scanner.

As for the synopsis script, I will take a look, it maybe as simple as changing " to ‘ in the script, but I will take a look when I can.

**Comment by Rocky5** [comment]
There are not videos in the artwork installer, when I have all games done it will be an addon as the videos are a lot larger than the artwork. 

As for synopsis emustation uses its own format. I have converted all Xbox synopsis from gamers over to emustation, so when you scan your games in it will extract and read this synopsis if it matches your games. (Make sure you’re using the detailed view, menu > UISettings)

**Comment by Vinoveg** [comment]
That’s what was thinking for the videos, I know that in the previous version of ES it was kind of linking the videos from a site/server or something.

I tried with the detailed menu but still no synopsis. Weird.

Just to make sure,
I downloaded the xbox artwork installer from the ES Downloader and extracted it on my E partition in ‘’Apps’’.
I ran the program’s xbe to start it.
I pressed A for an auto-install (and even B for a manual scan after because it wasn’t working).
I got back in ES, check the ‘’use resources artwork’’ box for the xbox games and scran my games manually.
I got all the artworks and I can also see them in file manager but still no synopsis. Hmmm..

It there something I did wrong?

De : John<mailto:notifications@github.com>
Envoyé le :April 22, 2020 8:39 AM
À : Rocky5/XBMC-Emustation<mailto:XBMC-Emustation@noreply.github.com>
Cc : Vinoveg<mailto:vincent.viger@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [Rocky5/XBMC-Emustation] Video previews (#38)


There are not videos in the artwork installer, when I have all games done it will be an addon as the videos are a lot larger than the artwork.

As for synopsis emustation uses its own format. I have converted all Xbox synopsis from gamers over to emustation, so when you scan your games in it will extract and read this synopsis if it matches your games. (Make sure you’re using the detailed view, menu > UISettings)

**Comment by Rocky5** [comment]
Check Q:\.emustation (or just emustation if using the test build) \synopsis\ is there a Xbox.zip or a Xbox folder?

If not update to the test build to get said zip and rescan your Xbox games again.

**Comment by Vinoveg** [comment]
Ahh! My error!

I deleted the zips in that folder because I use SkraperUI to get my synopsis.

Thank you for pointing that out! I guess everything is fine now!

I will show you my project when it’s done as you help me so much with it.

Thanks again it is very appreciated.

De : John<mailto:notifications@github.com>
Envoyé le :April 22, 2020 9:12 PM
À : Rocky5/XBMC-Emustation<mailto:XBMC-Emustation@noreply.github.com>
Cc : Vinoveg<mailto:vincent.viger@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [Rocky5/XBMC-Emustation] Video previews (#38)


Check Q:.emustation (or just emustation if using the test build) \synopsis\ is there a Xbox.zip or a Xbox folder?

If not update to the test build to get said zip and rescan your Xbox games again.

**Comment by Vinoveg** [comment]
Hi! Sorry to bother you again with my issues, feel free to answer when you want, no stress, just a quick question.

Started my xbox the other day, last time I played with it was months ago and everything was okay. Now the Genesis, GBA and Nes games lists won’t appear (black screen).

Log:

23:17:34 M: 37490688  NOTICE: -->Python Initialized<--
23:17:39 M: 36921344   ERROR: CLocalizeStrings::ClearBlock: Trying to clear non existent block Q:\emustation\scripts
23:17:39 M: 36921344  NOTICE: Auto video playback script exited properly
23:17:42 M: 37466112  NOTICE: -->Python Initialized<--


I reinstalled the whole thing but still don’t work. Before reinstalling I was unable to even update emustation nor download anything. Now it’s okay though but the Genesis, GBA, Nes still won’t start. Weird.

(I run the last test version available).

What do you think?

**Comment by Rocky5** [comment]
That log snipped you put says nothing really other than the video script exited correctly (when you went back to the carousel)

Black screen when loading a system means the gamelist.xml for that system is corrupt. This can happen if your roms have illegal characters that python doesn’t like.
