### ISSUE TITLE
Save filtering option for pal snes games

### ISSUE THREAD

**Issue by MrFilz** [Rocky5/XBMC-Emustation#39]
Everytime i start a snes pal game i have to go to the other video configurations to activate point filtering. Even when it is activated  in the menu, i have to do it, because no matter what, pal snes games are always blurred if i start them. Is there a way to save the settings so pal games are booted with point filtering enabled. This problem does not exist with ntsc roms. Point filtering is applied from the start...

**Comment by Rocky5** [comment]
Bug with the emulator, I have the same issue. Contact Madmab on emuxtras forum to see if he can fix the issue. (I suspect it’s not reading a config flag or something like that)
