### ISSUE TITLE
Amiga gamelist creation issue

### ISSUE THREAD

**Issue by TelaKeppi** [Rocky5/XBMC-Emustation#4]
I had some time to tinker with Winuaex and there's a slight issue with Amiga CD32 games. Winuaex currently support only ISO/MP3/CUE for CD based Amiga games. There's a double entry in games list when using ISO/CUE files. Command line launch with CUE file works like it should.

If it's too difficult to parse for 2 different types of Amiga games (disk images and cd images) CD32 could be it's own "console" like Sega 32x.

**Comment by Rocky5** [comment]
I will take a look, I don’t use that system so I will need to find a couple roms/disc to see.

**Comment by Rocky5** [comment]
Can you give me some more insight into the extensions? I can parse ISO/CUE fine but are CD32 files also .iso? as I will need to know so I can make it check for a matching CUE file and that way you wont get double entries.

**Comment by TelaKeppi** [comment]
I didn't check your code, but I just assumed since I got double entries with iso and cue files that the script just assumed all Amiga games are adf files (disk images) and thus didn't parse CD based games right. Yes, CD32 games are iso files, disk based games are adf files. Winuaex can use both.

**Comment by Rocky5** [comment]
Normally you keep the files zipped but I can add zip and adf support. Fixed parsing CUE/ISO files already.

**Comment by Rocky5** [comment]
I have it parsing zip, adf and CUE or ISO if an ISO has a matching CUE file it will skip adding the ISO entry.
Here you cant  test the script before I commit it.

https://pastebin.com/jNsSrevS

you have an hour before the link expires.

**Comment by TelaKeppi** [comment]
Ok, tested with iso/cue, adf and zip. Seems to be working fine now. Great!

**Comment by Rocky5** [comment]
Cool use that script until I commit the changes.
