### ISSUE TITLE
XBMC Emustation as Dashboard with Shortcut IGR issue

### ISSUE THREAD

**Issue by MrFilz** [Rocky5/XBMC-Emustation#41]
I made a shortcut with shortcut maker 2.0 to use XBMC Emustation as my default dashboard. Everything runs fine. It boots straight to XBMC Emustation if i power on the xbox. No problems with exit a game from an emulator via emulator menu. But if i start a xbox game, i use igr to go back to the dashboard. If i do so, my xbox boots twice. First very short, after that it cancels the boot sequence, starts another boot, and XBMC Emustation appears. Is this normal behavior? Is there another way to use XBMC Emustation as default Dashboard? 
My xbox is a tsop flashed winbond 1.4 system. Made it with Hexen 2018. Thanks for your efforts, i love the look of emustation!

**Comment by Rocky5** [comment]
If XBMC-Emustation is your default dash, then IGR’ing will take you back to it. As for the two reboots, do you ha e your bios IGR mode set to compatible? (This will do a full power cycle)

**Comment by MrFilz** [comment]
I am not a pro at these things, may i ask how i can do this?

**Comment by Rocky5** [comment]
> I am not a pro at these things, may i ask how i can do this?

Use hexen and use ind-bios5004.67 (if there is ind-bios5004.06 do not use it) Use .67 version. 

It will install a config to the root of C, edit this and change the IGRMode to 1, you can also set your boot locations in there.

**Comment by MrFilz** [comment]
Ok, so i have to use another bios. I will give it a try this week, thanks a lot!

**Comment by MrFilz** [comment]
I have flashed the ind bios, and changed the boot path to XBMC Emustation. And it works perfect. I did not change the igr mode, double boot is non existend nethertheless! Maybe the shortcut to XBMC Emustation together with the igr and my flashed Evox m8 bios caused the problem... 
Thanks for your help!

**Comment by Rocky5** [comment]
No problem :) glad you got it sorted.
