### ISSUE TITLE
URL Downloader - No Interweb access

### ISSUE THREAD

**Issue by jaytagdamian** [Rocky5/XBMC-Emustation#42]
In my local network, this line needed to be modified to allow URL Dowloader to work:

`socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("8.8.8.8", 53))`

I changed this to the IP of my router and port 80, soas to allow the script to continue, as port 53 is blocked on my router to forwarding traffic (i.e. local machines can only query the router for DNS, not the outside world.)

`socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("192.168.1.254", 80))`

You may not _want_ to patch this, but just for others searching for the same error message!

**Comment by chrisakak9** [comment]
Hi @jaytagdamian, I seem to be having the same/similar issue. when trying to run the URLDowndloader, I just get the message to check network cable. where do I edit the above code?

currently downloader version is 1.0.17

**Comment by Rocky5** [comment]
> Hi @jaytagdamian, I seem to be having the same/similar issue. when trying to run the URLDowndloader, I just get a message to check network cable. where do I edit the above code?
> 
> 
> 
> currently downloader version is 1.0.17

You will need to manually update, the IP used to check for a internet connection is dead 🤷‍♂️

Latest is v1.3.001 and is fixed.

**Comment by chrisakak9** [comment]
Thanks @Rocky5 sorry to ask but is there a guide to manually update? 

PS, you are an absolute legend for creating this!
