### ISSUE TITLE
Just upgraded 

### ISSUE THREAD

**Issue by petestoyshop** [Rocky5/XBMC-Emustation#43]
I just upgraded from another soft mod with the extras disc. The Xbox has an upgraded hard drive and now that I updated the partition g is gone and I can’t access the files that were there before I upgraded the mod. How to I get back the rest of the drive?

**Comment by Rocky5** [comment]
That’s a softmod issue not Emustation, but if using my softmod do the following. 

Applications > NKPatcher Settings > Hard Drive and enable F &G
