### ISSUE TITLE
Daphne games placement

### ISSUE THREAD

**Issue by 1ccs-todd** [Rocky5/XBMC-Emustation#45]
I placed my Daphne ROM binaries in zip format into ~\emulation\roms\daphne.  Scanning picked up all the ROM names as game titles.  I have tried every layout I can think of but the games will not play when the rest (MPEG & FrameFile) are in the same folder.  
I tried ~\emulation\roms\daphne\<game>.daphne\ as EmulationStation documentation suggests.
I tried ~\emulation\roms\daphne\<game>\ with everything pertinent to each game in this folder.  I also tried with individual Framefile & MPEG sufolders.
Editing my FrameFiles for each attempt, of course.

If I ignore EmulationStation configuration and place everything in ~\emulation\emulators\daphne\.  Then when EMUStation fails to launch the title the emulator falls back to it's own menu where I can succesfully launch/play each game.

Can we get launcher.py setup to parse the correct framefile and mpeg files for each game ROM files?  And have some documentation on what file layout is required.  Or have it changed to be a standalone launcher and use it's own menu to launch each game (like Atari Jaguar is).

Speaking of Atari Jaguar.... Why aren't special circumstances like this emulator documented in the main readme?  I have been stuck trying to list the games in ~\emulation\roms\atarijaguar\ and then found today (hidden in a closed issue) that it's games need to go to ~\emulation\emulators\atarijaguar\roms\.

**Comment by Rocky5** [comment]
The emulators probably doesn’t support command line launching of roms, I haven’t tested every single emulators. 

One that don’t have command line launching get marked as direct launch as they require there games to be in the main roms folder or if they have a config I can point them to the roms/<system> folder.

Also there isn’t really an official read me yet for ES, Gamers has one thanks to Cian and I suspect he will do one for ES at some point. 

I will also be cleaning up folders in roms folder as a few could be removed that aren’t or are crap emulated. 

Need any further info let me know, I will be updating ES at some point in the next couple weeks.

**Comment by 1ccs-todd** [comment]
The other ports of Daphne emulator support command line launching.   How can I throw some command line tests at it?
