### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jwrmo** [Rocky5/XBMC-Emustation#47]
Can you please direct me to where I can find documentation on getting these emulators set up. I have done the default installation of many of them in the .emustation/emulators and also have roms in .emustation/roms and many of the games dont work. So if you could direct me to where I can get docs on how to set these up and change various settings that need to be changed to get them working I would really appreciate it.

**Comment by Rocky5** [comment]
For the stable, roms should be zipped, or you need to add extensions to .emustation/scripts/file types/

Alternatively update to the test build and it’s a lot better when it comes to scanning stuff in. 

But on Xbox roms should be zipped, only ISO, Bin/CUE eg... don’t get zipped.

**Comment by jwrmo** [comment]
I was talking specifically about the settings that are asked when you click the rom name to play it. Specifically I am having trouble with Commodore 64 roms. There is a settings page that pops up after I click the rom. It would be nice if I knew what these do and what they are for.

    On Tuesday, September 29, 2020, 10:48:49 AM EDT, John <notifications@github.com> wrote:  
 
 


For the stable, roms should be zipped, or you need to add extensions to .emustation/scripts/file types/

Alternatively update to the test build and it’s a lot better when it comes to scanning stuff in.

But on Xbox roms should be zipped, only ISO, Bin/CUE eg... don’t get zipped.

**Comment by Rocky5** [comment]
Ah ok, I can’t help you there as I haven’t used that emulator. Emuxtras forum is where you want to go for info on emulators. As that’s where they are hosted and people still update them to this day. Though not many.
