### ISSUE TITLE
offline?

### ISSUE THREAD

**Issue by calebTree** [Rocky5/XBMC-Emustation#49]
Fresh install connects and says update available. Next, URL Downloader keeps reporting network error. Network status page?

**Comment by Rocky5** [comment]
I know, it's because of the IP I used for detecting if there is a online connection. It's down and not sure if it will be back up 🤷‍♂️

It may require a manually update by users to fix.

**Comment by Rocky5** [comment]
Yeah I forgot to update the script on here, will do it now.  
> Fresh install connects and says update available. Next, URL Downloader keeps reporting network error. Network status page?

**Comment by Rocky5** [comment]
Should be fixed now.

**Comment by calebTree** [comment]
No worries, you're awesome!
