### ISSUE TITLE
Samba rom location

### ISSUE THREAD

**Issue by danyboy666** [Rocky5/XBMC-Emustation#5]
Is there a way to load roms from smb network location? I see the settings and shares from the main XBMC options but I can't set this path for roms auto scan in the main Emustation gui.

**Comment by Rocky5** [comment]
This is not an issue so please don’t use this to asks questions. 

No you can’t use SMB shares, it must all be on the Xbox.

**Comment by danyboy666** [comment]
My mistake sorry about this and thanks for the info.
