### ISSUE TITLE
Newest package structure does not match installation instructions

### ISSUE THREAD

**Issue by twilbrand** [Rocky5/XBMC-Emustation#51]
The instructions on the main page of this project ([here](https://github.com/Rocky5/XBMC-Emustation)) Mention :

```
You place your roms in the designated subdirectory in the .emustation\roms folder.
Same exact thing for the emulators, but in the .emustation\emulators folder.
```

However the package downloaded by clicking the "Download Prebuilt versions: Download XBMC-Emustation" link on that same page contains directories that do not match those instructions.  There is no `.emustation` folder and inside the closely named `emustation` folder there is no `roms` folder.

Is something missing from the latest build or should users make their own `roms` folder inside the `emustation` folder and created correctly named system folders under `roms` themselves?

**Comment by Rocky5** [comment]
Transfer it over first and do the initial setup, it will create all the folders for you once done. 

I will need to update the readme.md file.

**Comment by kidxuno** [comment]
Hey Rocky, having a similar issue. I have created the emustation folder, transferred it, and initiated the setup but the roms folder is still missing from the emustation folder? 

Also in the emustation UI, the carosel only displays favorites and options but not the other emulators that are within the emustations folder.

**Comment by Rocky5** [comment]
> Hey Rocky, having a similar issue. I have created the emustation folder, transferred it, and initiated the setup but the roms folder is still missing from the emustation folder? 
> 
> 
> 
> Also in the emustation UI, the carosel only displays favorites and options but not the other emulators that are within the emustations folder. 

Sorry, on the carousel press start and in the scanner > scanner options, pick refresh carousel. 

Seems I removed the creation of the roms folders on initial setup 😒

Will need to amend that also 😂

**Comment by kidxuno** [comment]
Awesome, thanks for the support. Looking forward to the update.

Also, followed your instructions to refresh carousel. The initization was complete but it's still the same look. Maybe I have to wait for the update to the XBMC?

**Comment by Rocky5** [comment]
> Awesome, thanks for the support. Looking forward to the update.
> 
> 
> 
> Also, followed your instructions to refresh carousel. The initialization was complete but it's still the same look. Maybe I have to wait for the update to the XBMC? 

You need to add roms, or have your Xbox games in E,F or G:\Games and scan them in. Same for the ports menu, E,F or G:\ports or homebrew

**Comment by kidxuno** [comment]
Got it! It all works now. Thanks a bunch. 

Last question, the synopsis is said to only work with rom sets from resurectionxtra so I downloaded sets for psx and genesis. I FTP the zips over to the correct rom folders, scanned them, but they only appear as an independent file in the emulator. Then it asks which file do i want to open 7z.002 or 7z. 003 and they both just freeze the system. Do I need to extract the files?

**Comment by Rocky5** [comment]
> Got it! It all works now. Thanks a bunch. 
> 
> 
> 
> Last question, the synopsis is said to only work with rom sets from resurectionxtra so I downloaded sets for psx and genesis. I FTP the zips over to the correct rom folders, scanned them, but they only appear as an independent file in the emulator. Then it asks which file do i want to open 7z.002 or 7z. 003 and they both just freeze the system. Do I need to extract the files? 

You need to extract the 7z files to get the zipped roms, you then transfer the zipped forms over.
