### ISSUE TITLE
Emustation altering 

### ISSUE THREAD

**Issue by kidxuno** [Rocky5/XBMC-Emustation#53]
Hey there, 

I have xbmc 4 gamers and emustation installed on my box but I recently upgraded the stock hdd and made sure to clone the stock to the new. Everything works well but now I'm wondering how to transfer the emustation from E: to F: Or G: partitions where all the free space is located?

 I tried to use the xbmx file Manager but i backed out mid process and got an error upon bootup that took forever to find the fix, so I'm looking for the safest process. Thanks in advance!

**Comment by Rocky5** [comment]
> Hey there, 
> 
> 
> 
> I have xbmc 4 gamers and emustation installed on my box but I recently upgraded the stock hdd and made sure to clone the stock to the new. Everything works well but now I'm wondering how to transfer the emustation from E: to F: Or G: partitions where all the free space is located?
> 
> 
> 
>  I tried to use the xbmx file Manager but i backed out mid process and got an error upon bootup that took forever to find the fix, so I'm looking for the safest process. Thanks in advance! 

Make sure your F and G partitions are formatted correctly (64kb clusters)

Use unleashX to copy the folders to the larger partitions. But I recommend you keep emustation on E and move the emulators, media dna roms folders to the larger partition s. Reason being E is the fastest partition and if you move it to F or G the more you fill it the longer it will take you to get into the game lists. (Lists are built when you press A on a system)
