### ISSUE TITLE
XBMCE does not show NEC PC-98 rom files

### ISSUE THREAD

**Issue by RoofTop1** [Rocky5/XBMC-Emustation#55]
XBMC-Emustation does not show NEC PC-98 rom files -- and there is also no pc-98 logo on carousel.
They rom's use the .fdi or .hdi extension.

If you zip the rom files xbmc-emustation will display the games. 

But the nec pc-98 emulator does not support zip files.

**Comment by Rocky5** [comment]
Add custom extensions to Q:\emustation\scripts\file types\
