### ISSUE TITLE
Missing ROMS directory

### ISSUE THREAD

**Issue by xasapricky** [Rocky5/XBMC-Emustation#59]
Prebuilt installation and build .bat is missing ROMS directory + subdirectories. 

Built from .bat
![image](https://user-images.githubusercontent.com/78287823/106373498-3ba4c900-63ce-11eb-80b8-9a9a3a91e285.png)

Pre-built (appears to be missing other directories too?)
![image](https://user-images.githubusercontent.com/78287823/106373522-6ee75800-63ce-11eb-8008-a69e17f6cb3b.png)
![image](https://user-images.githubusercontent.com/78287823/106373526-773f9300-63ce-11eb-902e-493d35c5bb7b.png)

Am I missing some critical step? Love your work.

**Comment by Rocky5** [comment]
Directories are populated when the initial setup is done on the Xbox.
