### ISSUE TITLE
create_rom_lists.py crashes on scanning N64 ROMs

### ISSUE THREAD

**Issue by johannesgunnar** [Rocky5/XBMC-Emustation#6]
When auto scanning systems create_rom_lists.py fails only with the following error on N64 ROMS

```
Error
Script failed! : create_rom_lists.py
```
Is there anyway to see more verbose error output to see on what game or why this script might be crashing?

**Comment by Rocky5** [comment]
Reupdate I forgot to put modules in the build.

**Comment by Rocky5** [comment]
Also the XBMC.log will give you the error report.

**Comment by Rocky5** [comment]
Can you stop opening issues please that’s not an issue, you must use a specific rom set with N64 as the emulators is crap and the roms set has all roms that work coiffured to do so. 

PM me somehow as I don’t want to keep closing these for issues that are documents on the Facebook groups or forums. 

Earthwormjames 188 Compilation
