### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Mr-Xbox** [Rocky5/XBMC-Emustation#61]
Love your work :)
Just wanted to point out that cancel button is missing the 'L'

Also in a future version can you allow a section where artwork might either be contributed or harvested/collected as I'm sure there are others out there that have made artwork files.

**Comment by Rocky5** [comment]
I know it’s been a year 🙈 but where in the files did I miss the L?

As it should be using the built in language file for those buttons etc…

**Comment by Mr-Xbox** [comment]
Have recently moved house to Mitchell so have to connect the xbox  back up.
Will have more details for you within 24 hours and if needed a screen shoot.

Thanks again for all your hard work.

**Comment by Mr-Xbox** [comment]
Hi Rocky,

Sorry for dragging my arse but for the life of me I can’t find the mistake. I can’t even find a screen with a cancel button ☹

 

If I find it I’ll surely let you know.

If you know where the cancel buttons are I think it may have been in a box/button a few pixels short so displayed the word but the l didn’t fit so I wouldn’t have seen it, So not really a spelling mistake, more a size/font error. But don’t sweat on it, You’ve done a really good job and I really admire anyone with your talent.

 

Thanks again and if I could, I would send something to you.

Tony Waldron

Mitchell, QLD, Australia

 

Ps: is it worth doing a GoFoundMe page to found the next project?

 

CONFIDENTIALITY: This message and any attachment/s are confidential and may be privileged or otherwise protected from disclosure. If you have received it by mistake, please let me know by reply and then delete it from your system; you should not copy the message or disclose its contents to anyone.
