### ISSUE TITLE
Google drive quota error.

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Rocky5/XBMC-Emustation#62]
I just recently installed this and I was going to add emulators and the downloader no longer works... and they say OG Xbox is still relevant... THE SCENE is DEAD AS A DOORNAIL, just like PS3, NDS, and PSP homebrew scenes are.

**Comment by Rocky5** [comment]
What version did you install? and yes sometimes if to many folk downloads from the downloader (lots of large files) it gets paused for a few hours to a day. 

This is the joys for free downloads.

**Comment by RetroSoftwareRepository** [comment]
I installed the latest version. Not like I’m expecting much.... I was expecting a more up to date version of Surreal64 CE... with no graphical problems with hacks or translations. The mentioned emulator seems to be dead development wise which is really sad.

**Comment by jessenic** [comment]
> What version did you install? and yes sometimes if to many folk downloads from the downloader (lots of large files) it gets paused for a few hours to a day.
> 
> This is the joys for free downloads.

I've been trying to download things via XBMC4Gamers, same GDrive error.

I chatted with the guys over at Digiex, they could be able to provide you with quota-free download hosting for free if it's not too many gigs of files you need to host. Could you PM InsaneNutter on Digiex if you're interested: https://digiex.net/members/insanenutter.2/

**Comment by KPackratt2k** [comment]
Can't you guys use MEGA to host the downloads for the XBMC Emustation add-ons instead of Google Drive? They don't have daily quotas unlike Google Drive. Just a suggestion.

**Comment by Rocky5** [comment]
> Can't you guys use MEGA to host the downloads for the XBMC Emustation add-ons instead of Google Drive? They don't have daily quotas unlike Google Drive. Just a suggestion.

Cannot use mega sorry, that also has a quota unless you pay.
(2GB every so many hours am sure it is)

**Comment by KPackratt2k** [comment]
> Cannot use mega sorry, that also has a quota unless you pay. (2GB every so many hours am sure it is)

Oh, you're right. I guess I just wasn't using MEGA enough to notice that they had a download quota too. I looked it up and indeed they have a 5GB download limit. I feel so embarrassed. I guess there is no such thing as a perfect file hosting service.

I apologize for any confusions I may have caused with my posts here.

**Comment by jessenic** [comment]
> > Can't you guys use MEGA to host the downloads for the XBMC Emustation add-ons instead of Google Drive? They don't have daily quotas unlike Google Drive. Just a suggestion.
> 
> Cannot use mega sorry, that also has a quota unless you pay. (2GB every so many hours am sure it is)

Btw did you end up reaching out to Digiex?
