### ISSUE TITLE
4096 files limitation

### ISSUE THREAD

**Issue by 4bitFox** [Rocky5/XBMC-Emustation#63]
I just ran into the filesystem-limitation of 4096 files per folder while copying roms from my PC to my XBox. 
(pce-cd specifically)

Being able to make a pce-cd2 folder for example might work?

PS: Do I have to put the .mp3 file in there or are the .iso files enough (Resurrection Xtras roms).
Not having to copy the .mp3 files would prevent me from reaching 4096 files.

**Comment by Rocky5** [comment]
Put some in, run the scanner and it will folderize them (put them into folders) add more and repeat.

**Comment by Rocky5** [comment]
mp3s must have the same name in there name as the main IOS/CUE file. Or they won’t be moved into the folder along with the ISO/CUE

**Comment by 4bitFox** [comment]
Thanks. I didn't know that :)
