### ISSUE TITLE
xbmc-emustation crashes with favorites tile  

### ISSUE THREAD

**Issue by oddstap** [Rocky5/XBMC-Emustation#64]
Hello, I am a fan of this frontend and wanted to shoot a quick message about a problem I've encountered.

While using emustation it will crash if you stay on the favorites tile too long, the quick fix for this is to just disable it in the menu which I have but thought it would be a good idea to share my findings in the hope it'll help improve this project.

This is what happens when I bootup emustation from XBMC, i have used emustation as the default on evodash but it does the same thing.
https://user-images.githubusercontent.com/41316908/112716522-e27c8180-8eb4-11eb-822f-51aafa142cc0.mp4

I found out it was the favorites tile by quickly tapping the D-pad during boot but as shown in the video below if left on the favorites tile it will crash 
https://user-images.githubusercontent.com/41316908/112716557-15267a00-8eb5-11eb-9804-91e0db7edfdd.mp4

My Xbox is a v1.0 with an openxenium modchip and makemhz HDMI mod, I have tried M8+ lba48 patched and ind-bios 5004.67 they both have the same issue with this crash.

If you need any more information please let me know I hope I can help out in anyway and thanks for this awesome frontend.

**Comment by Rocky5** [comment]
Yeah it seems to be the hdmi digital adaptor that causes it, you ain’t the only one. Gamers does it also and normal XBMC according to some on FB groups. 

When the homescreen loads it’s not doing anything fancy, it’s just sitting there. Do you have a startup playlist enabled?

Also thank you for the video, that helps a lot and wish everyone done it 😂

**Comment by oddstap** [comment]
No I don't have playlists, its a pretty fresh install so haven't had time to play around too much. 

I have experienced issues with XBMC specifically only with certain themes. I haven't had time to really test xbmc4gamers though.  if you want I can try and recreate the crash using certain themes on XBMC like PM3.HD whereas I don't experience the crash using themes like Confluence lite. 

I have also un-crashed emustation by placing a disc in it while it was crashed. 

I also weirdly enough have better stability of xbmc and emustation when opening them up from another dashboard, although this could be placebo

>Also thank you for the video, that helps a lot and wish everyone done it 😂

your welcome, while researching this issue I saw how many people there was asking you kind of dumb questions so I wanted to make sure I did my best to make this easier for you lol

**Comment by Rocky5** [comment]
Right so it’s not crashing, it’s halting for some reason. (Why when a disc is inserted it’s jumping to the disc icon)

can you load ES and hold X and Y together until it loads, wait till it doesn’t accept input and then FTP in and grab the log from Q:\system\ please and send me it. (You should see info on the top left of the screen when the buttons are held on boot)

I want to see if there is anything in there.

**Comment by oddstap** [comment]
Ok, so maybe it is a crash after all because I was unable to establish an FTP connection after the crash/halt, I noticed that the previous session will get saved to ("xbmc.old.log") so I did establish an FTP connection before recreating the crash to try and capture something. 

![FTP_FAIL](https://user-images.githubusercontent.com/41316908/112753339-d10ea480-8f9c-11eb-8622-a7f573ab757a.PNG)

Not sure if it'll help but here is the two log files from this.
[xbmc.log](https://github.com/Rocky5/XBMC-Emustation/files/6217305/xbmc.log)
[xbmc.old.log](https://github.com/Rocky5/XBMC-Emustation/files/6217306/xbmc.old.log)

I did come up with the idea to put a disc in to uncrash it and maybe it would give more information however was unable to replicate the uncrash with the disc, maybe i was mistaken or it was some strange fluke.

I also tried to opening up ES in XBMC to replicate the same conditions as last time and was still unable to get it to go to the disc icon tile.

**Comment by Rocky5** [comment]
Thank you, both those logs show nothing out of the norm. 

See the bios you’re using are they all HDMI patched? I ask because if they are invalid it maybe causing XBMC to panic. But that’s a stretch as I know XBMC can dump the bios and check if it’s in a md5 hash list for the info screen. 

As I can’t see any issues in those logs 🤷‍♂️

**Comment by oddstap** [comment]
I'm only using the LBA48 patch with M8+, I wasn't able to get the HDMI and LBA48 patch to work together. I also experienced strange behavior with using different bios. but I wont go into detail unless you want to hear. I'm pretty new to all this so maybe I'm not applying the patches in right order.

I'm gonna play around with the bios and see if I cant find a solution, Thanks for all your help sorry I couldn't have been more helpful.

**Comment by Rocky5** [comment]
Load the M8plus bios in EVTOOL or what ever it’s called and enable the partition table bottom left of the window. You can now patch the bios with the makemhz patch.

Then all you need to do is write a partition table to the Xbox hdd using XBPartitioner and your petitions will show. 

LBA48 patches are useless in this day and age. 

If different bios are causing issues then it’s not specific to ES/Gamers/XBMC. As the
Bios should have zero effect on these dashboards. 

But try patching the bios like I said above, I know it works as someone else said the same as you and you need to do the bios edits first before patching it. (As EVTOOL will say it’s an invalid bios)

**Comment by oddstap** [comment]
Ok, I used my previously LBA48 patched bios and applied the HDMI patch last. This time the bios booted so I was doing it in the wrong order, However unfortunately It still crashed so I think the issue is independent of bios. 

I also did press start during the crash, it does nothing. also tried IGR and nothing either.

I did think about switching out the icon/image used for the favorites title in ES to see if that would make any difference, I don't want to make this thread longer than It needs to be or waste your time though since this is most likely a HDMI issue with homebrew.

**Comment by Rocky5** [comment]
Nah we need to see if we can fix it 😂 you can disable the favourites tab, so when you load move so it doesn’t crash, press start > UISettings and you can disable it in there. See if it still crashes afterwards.

**Comment by oddstap** [comment]
Oh that's what I've been doing to avoid the crash works pretty well except sometimes will just crash randomly, I believe I did get it to crash in the options menu and I know for a fact it has crashed while looking through artwork for Xbox games. 

however the frequency of the crashes are random and so far apart its not really an issue. I mean its annoying but its not something I can recreate as easily as say the favorites tile. 

Very strange, maybe something about displaying image files with HDMI mod causes these crashes? because in all crashes it happened while displaying an image in either a menu or tile and its the same with XMBC and the themes that use very detailed icons in the menu. so maybe a possible lead? then again I'm not an expert.

**Comment by oddstap** [comment]
Update found a solution that seems to work quite well, just change the resolution from 720p 16:9 to 480p 4:3

Maybe a RAM upgrade would help stability for 720p idk but all I know is no crashes as of it with the resolution set to 480p.
Kinda ironic that i tired to get the best picture quality out of an Xbox and got stuck with 480p dashboards lol but its whatever.

Gonna try a upgraded xbox with more RAM to see if the issue is helped in the near future.

**Comment by Rocky5** [comment]
Yeah I know it’s 720p doing it. It’s the makemhz adaptor that causes it. I thought I said that further up sorry. It’s more prone on v1.0/1 boards v1.4 boards don’t seem to have the issue. 

It’s not a ram issue, as there would be ram notifications in the logs of XBMC. it’s just what ever the device is doing it craps out.
