### ISSUE TITLE
URL Downloader freezing at random moments

### ISSUE THREAD

**Issue by Chevan94** [Rocky5/XBMC-Emustation#65]
Hello,

It's borderline impossible for me to download any large file due to the downloader freezing the download at completely random intervals (sometimes at the beginning, sometimes at the end). Just gets stuck, I'm unable to cancel right away but if I succeed i get a script error (urldownloader) after I try to download again.

This requires me to restart the console to be able to download.

I've cleared the caches again and again, reinstalled xbmc and it still freezes. It can even freeze on the 10 MB download sometimes...

**Comment by Rocky5** [comment]
Send me the 2 .log files from the system folder when it does it. As that may tell me why it’s happening.

**Comment by Chevan94** [comment]
Log files attached
[xbmc.log](https://github.com/Rocky5/XBMC-Emustation/files/6371630/xbmc.log)
Attaching the logs
[xbmc.old.log](https://github.com/Rocky5/XBMC-Emustation/files/6371632/xbmc.old.log)

**Comment by Rocky5** [comment]
Thank you, 2 things from the xbmc.log. It can’t delete the files on your cache partition and secondly you’re running out of memory. 

Are you using any themes?
What resolution is your Xbox running at?
What Xbox version are you using?

**Comment by Chevan94** [comment]
This is a 1.6 Xbox.
I recently got a component cable, so 720p on a Carbon Alt theme, but this issue also existed when I used the SCART cable on a simple theme, so it was 480i.

The script froze on around the line in the log that says "11:13:22 M: 16252928   ERROR: No list with supported IDs, so random script didn't work :D"
Everything after that is after I 'force cancelled' the download and tried downloading again.

**Comment by Rocky5** [comment]
The part you said it the random script running but no control ID it looks for us there, hence the notice. 

But prior to that I can’t see anything that would cause it. Try downloading something smaller and if it crashes/hangs for more than 5 mins send me the logs please. 

I use google drive so if they are having issues it effects everyone unfortunately.

**Comment by Chevan94** [comment]
[xbmc.log](https://github.com/Rocky5/XBMC-Emustation/files/6372064/xbmc.log)
I kept it frozen for half an hour, nothing is seen in the logs.
I then started pressing all the buttons on the controller and it eventually crashed out of the downloader, I guess I triggered some sort of a reset of UI.

After that I tried to download again with the permission denied error.
[xbmc.log](https://github.com/Rocky5/XBMC-Emustation/files/6372069/xbmc.log)
I was able to download something else successfully after it crashed (something smaller)

Seems like the script is stuck in the background somewhere and it still tries to download the other file.

**Comment by Rocky5** [comment]
If you push the Left stick in it will reload the skin, but python will still run in the background, you just reset the OSD.

Can you record me a video from boot to downloading a file please? 

So I can see what’s going on as the logs don’t show me any issues. 

Note, it can’t take a while for it to download a file, as it depends on Google’s servers and where the files are in the world.

**Comment by Chevan94** [comment]
https://user-images.githubusercontent.com/83143351/115997792-b99af980-a5e4-11eb-9bb2-ed63d11254b2.mp4
Here's the video.
It froze at the ETA 7 min 2 sec, the hard drive head stopped making noises so it wasn't doing anything

Logs:
[xbmc.old.log](https://github.com/Rocky5/XBMC-Emustation/files/6372202/xbmc.old.log)
.

**Comment by Rocky5** [comment]
Thank you for the video, ok so the fact it still responds means it not crashed, it looks like it more likely google, your ISP or the Xbox hdd. 
(If it was crashing/hanging you wouldn’t be able to cancel)

Also the fact the file on the cache partition is write protected means it more than likely your HDD or adaptor if a data drive. As once you cancel it exit out of python and that file should be removable. 

What size drive is it? Do you have an sata adaptor eg...?

**Comment by Chevan94** [comment]
I'm actually not able to cancel, that refresh in the video was me reloading the UI with a left stick.

It's a standard 80 GB IDE drive, more specifically WD800JB. It's connected with a stock 40 wire IDE cable but the same was happening when I swapped it for the 80 wire one.
I haven't tried on a different drive yet as I don't any any at hand. I'm going to swap the drive to a larger one anyway once the SATA adapter and the 250GB IDE drive arrives, I'll use the most compatible solution (either a 320GB SATA or that 250GB IDE)

I've been monitoring the Ethernet port of the Xbox from the router and it's transferring absolutely nothing during the freeze.
