### ISSUE TITLE
When Running Scan For Games, I Get A Create_Roms_LIst.py Error

### ISSUE THREAD

**Issue by Guybrush3pwood83** [Rocky5/XBMC-Emustation#69]
When I try an automatic scan, or when I specifically scan the Xbox games category, it crashes with a "Create_Roms_LIst.py" error. Checking the error log under Q:\system\ I get:

23:07:18 M: 35049472   ERROR: --> ------------------------------------------ <--
23:07:18 M: 35049472   ERROR: --> Python script returned the following error <--
23:07:18 M: 35049472   ERROR: --> ------------------------------------------ <--
23:07:18 M: 35049472   ERROR: Error Type: <class 'struct.error'>
23:07:18 M: 35049472   ERROR: Error Contents: unpack requires a string argument of length 4
23:07:18 M: 35045376   ERROR: Traceback (most recent call last):
                                              File "Q:\emustation\scripts\create_rom_lists.py", line 1454, in <module>
                                                Main_Code()
                                              File "Q:\emustation\scripts\create_rom_lists.py", line 467, in Main_Code
                                                XBEInfo = Extract_XbeInfo(XBEFile).split('|')
                                              File "Q:\emustation\scripts\create_rom_lists.py", line 57, in Extract_XbeInfo
                                                IdData		=	struct.unpack('L',tIdData)
                                            error: unpack requires a string argument of length 4
23:07:18 M: 35045376   ERROR: --> --------------------------------- <--
23:07:18 M: 35045376   ERROR: --> End of Python script error report <--
23:07:18 M: 35045376   ERROR: --> --------------------------------- <--

Any ideas?

**Comment by Rocky5** [comment]
It’s your Xbox games or homebrew games. 

One of your xbe files is corrupt. The latest version of XBMC-Emustation should write the current games name in the log, and I don’t see it above. 
(this makes it easier to find the game that has the corrupt xbe)
