### ISSUE TITLE
XBOX Games Artwork Dowload freezes

### ISSUE THREAD

**Issue by MichMangen** [Rocky5/XBMC-Emustation#7]
Hi Rocky5, great work so far!
I‘ve got several issues. Perhaps you can help:
1. I‘ve tried to download the Xbox Artwork several times, but had a freeze every time at 60+ %.
2. Some Snes and Nes Roms are not recognized (it‘s the No Intro collection) by the name identifier an hence there is no artwork.
3. The Menu with the several carts image is empty. What is this folder for?
4. Is there a way to integrate Coinops 8?
Thx,
Mich

**Comment by Rocky5** [comment]
1. Format your Cache Partitions as this is where the file is downloaded to.

2. No my problem, you must get the artwork yourself as the artwork in the downloader is for the RessurectionXtras rom sets.

3. Favourites

4. Add it to the home menu. Menu > UI Settings > Home Screen Customization > Press Down

None of what you have asked is an issue with Emustation, so please refrain from asking questions using this system.

You can use the OGXbox forums or the OGXbox facebook group to get a hold of me.

**Comment by MichMangen** [comment]
Hi John. Thank you for the fast reply.
I thought 1+2 could be Emustation problems. I‘m sorry for bothering you in the wrong place. CU soon. Thank you very much, Mich

**Comment by Rocky5** [comment]
1. is a HDD problem your cache partition is corrupt or something is wrong with it, Its not a dashboard issue.

2. Again this is your problem, you use different roms that the artwork is not made for then that falls on you. I cant hash roms as people use all different ones and it's to much of a pain to cater to ever rom out there.

**Comment by MichMangen** [comment]
Hi John, thanks again.

 I didn‘t have problems with the harddisk till now and it‘s brandnew. How do I check if if there‘s corrupt data? Which partition could be corrupt to make the xbox freeze with the artwork download? It‘s only when I dowload the xbox artwork, so it could be a matter of size perhaps. The other artworks (nes, snes and megadrive) were downloaded without problems...

Regards,

Mich

**Comment by Rocky5** [comment]
The partition used to store the download is the X partition.

Download the cache formatter from the other tab in the downloader.

**Comment by MichMangen** [comment]
Great. Thank you, John. I‘ll try that and keep you posted. I wish you a good night.

**Comment by MichMangen** [comment]
Hi John,

The problem is solved 😊. Thank you very much. 

Perhaps I did something wrong but the icons aren’t box icons like the Emulator games. I think I‘ll try to make Artwork and Fanart myself.

I haven‘t tried the hint you gave me for Coinops yet.

I may have found an issue: the Xbox freezes when I‘m selecting „Edit Xbox game“.

All in all it‘s a really cool and good looking system (the best looking on Earth) and I‘m looking forward to using it when it‘s ready 🙂.

Regards,

Mich

**Comment by MichMangen** [comment]
Ok, I‘ll try that tomorrow. Thanks again.

Good night,

Mich

**Comment by MichMangen** [comment]
Hi John,

The Xbox Artwork is working now and Coinops has found his place too. Thank you very much 😊.

Last thing I have to do now is putting the missing artwork (a few games like for example Panzer Dragoon Orta and Baldur‘s Gate Dark Alliance 1) in the right place. Nearly all of the Gameboy Advance Artworks weren‘t found though. Tomorrow I‘ll give it a second try. Perhaps I did something wrong.

I really happy. With your help I made of a broken Xbox something really special 😊👌.

Regards,

Mich

**Comment by MichMangen** [comment]
Hi John,

Unfortunately the „Xbox games edit mode“ is still freezing during startup. The the spinning icon in the upper left corner appears but doesn‘t spin.

Could you explain me how I can rename the roms / Xbox games and their info, boxart and fanart?

The synopsis changed the names of the games but they were too long to fit the screen or not really clean.

Thanks again,

Mich

**Comment by Rocky5** [comment]
One of your games must have a corrupt xbe.

Don’t use the synopsis names when asked if you would like to use them and it will use the file names of the roms. Or if you want to edit a few thousand txt files Q:\.emustation\synopsis\ 

Box art uses the roms filename with .jpg extension ( even if they are .png you must rename them to .jpg ) if you don’t next time you scan the roms in it will do that for you.
Q:\.emustation\media\

Xbox games don’t use synopsis names, they use what ever the xbe files title name is. It’s only roms that I allow the use of the synopsis names. So edit the xbe files title name ( edit mode ) and rescan your Xbox games to update the names, or edit the gamelist.xml for Xbox. ( Q:\.emustation\gamelists\ ) 

Yeah everything is in the .emustation folder.

Everything that’s a rom/emulated, artwork and synopsis use file names to match content.
The Xbox uses titleids to match content. ( since to many folk rename crap )

**Comment by MichMangen** [comment]
Great thank you. I‘ll give it a try tonight.

How can I find out which game has a corrupted xbe? 

Sorry, I‘m into computing since the Commodore 128, but I have never dived deep into programming or theory. I‘m a typical user.

Now I‘m collecting vintage consoles and computers, but unfortunately I still have not much time to dive deep into the theory. I‘m trying to make most of the little time I have 😉.

Thanks again. Warm greetings from Luxembourg.

Mich

**Comment by Rocky5** [comment]
Simplest way is to put a boot disc ( Helen or some other boot disc ) into the Xbox m, now enter edit mode let the system hang and power off an on. Now FTP in and grab the XBMC.log from the system folder. 

In there it will have listed the games as they are scanned in. The last one in the list will be the culprit or the one just after that game. 

Alternativly just disable the fast game loading. Q:\\system\toggles\ just rename it and then enter edit mode. It will hang but you will have a dialog onscreen listing the games it’s scanning.

**Comment by MichMangen** [comment]
Hi,

How are you?

I need your help. I tried to install the Artwork installer v1.6 and it freezes every time as soon as the Extracting screen appears.




Regards,

Mich

**Comment by Rocky5** [comment]
Make sure you have the proper amount of space, if it continues to happen use the cache formatter app in the other tab. (Or use unleashx for format the cache partitions)

**Comment by MichMangen** [comment]
Hi John. 

Thank you for answering.

I deleted the artwork and formatted the cache twice. No change.

What could I do to try and make it a „clean“ system and start like new without deleting the games?

Mich

**Comment by bezsenny80** [comment]
Hi John, first at all i wana say You did great job with xmbc4gamers, 
I need to ask You about artwork instaler 1.7, on downloader it saids You need about 540MB Free space the thing is iGot only 145mb on c: but 175000 on F: when i try to download instaler it saids not enought space on c: is any way how i can download and instal it on my f: partition? 
Thanks

**Comment by Rocky5** [comment]
No it gets installed to the internal scripts folder, I always recommend running gamers or emustation from E as that will give the best performance, especially for emustation loading menus. (As these are created on each menu entry) with emustation you can move the large folders out to a different partition.

**Comment by bezsenny80** [comment]
Thanks for quick answer, so what is the best option for me now, i dont wona
mess my games and emulators, what i can do?, as well after i install xmbc
4gamers i realized that my save from NFS game not exist any more, is  it
diferen place for saves? Sorry if anny of my questions ar weird or
something  i first time softmoded my xbox  i like the way with yours rocky5
mod, but propably i made many mistakes (like small c partition) i dont know
what i can relocate without messing my retro stuff and games for og xbox

**Comment by Rocky5** [comment]
You got it installed in C:\dashboard? If you do you can use the dashboard restore and back up option in NKPatcher Setting > Dashboards to move it to E, or you can copy it manually. 

I tried to cover all bases with my softmod. 

Saves shouldn’t vanish, so not sure what’s happened there as none are touched.

**Comment by bezsenny80** [comment]
Ok saves are not problem it was luckily only one game save, about dshboard
i generated new xbmc4gamers folder on pc and ftp to c:      ( can i  safely
move it to F: and it still be works? On c: i got folder dashboard and
folder xbmc4gamers)

**Comment by bezsenny80** [comment]
Johny You are a my hero, i use a file manager and move dashboard and
xbmc4gamers folder to e: and now its start downloading Artwork instaler ;).
Thanks
