### ISSUE TITLE
issues with Surreal64

### ISSUE THREAD

**Issue by leov30** [Rocky5/XBMC-Emustation#70]
issue:
trying to run games (like Super Mario 64) crashes the emulator or loads the incorrect setting for other games.

I found that this files were corrupted from the downloader, replacing them fixes the some of the issues

1964.ini
1964x085-510.xbe
1964_11.ini
1964_21.ini
ultra.ini

I also found that in "create_rom_lists.py" the core indexes are switched around, this are the correct ones:

if N64_Emu_Core == "pj64x14": N64_Emu_Core = "3"
if N64_Emu_Core == "pj64x16": N64_Emu_Core = "1"

**Comment by Rocky5** [comment]
I will have a look, I did reupload a clean copy of sureal as the files were corrupt before. 

I will also make the changes to the scan script 👍
