### ISSUE TITLE
Force 480p on all games

### ISSUE THREAD

**Issue by filevans** [Rocky5/XBMC-Emustation#71]
Hello

Please is there a way to force 480p on Pro Race Driver 1 / TOCA Race Driver and also Ultra Bust-a-move / Ultra Puzzle Bobble ? They are 480i only and they're the only games I can't find hex codes for, is there a way to force them to 480p using EmuStation?

Thank you very much

**Comment by Rocky5** [comment]
It’s a bios issue, you will need to force it at the softmod level or the bios level (hardmod)

**Comment by filevans** [comment]
Please could you make a 480p hex code just for Pro Race Driver 1 / Toca Pro Race Driver? as none of the generic codes are found in its xbe and it's now the only game I can't force to 480p, I didn't want to switch my console totally to 480p because I also use it to run amiga, c64 emulators in 50hz so I need to still access 576i

Thanks a lot for your help

**Comment by Rocky5** [comment]
> Please could you make a 480p hex code just for Pro Race Driver 1 / Toca Pro Race Driver? as none of the generic codes are found in its xbe and it's now the only game I can't force to 480p, I didn't want to switch my console totally to 480p because I also use it to run amiga, c64 emulators in 50hz so I need to still access 576i
> 
> Thanks a lot for your help

it might be one of the games that just dont have the switch in the code and you need to force it at the kernel level.

I will take a look, but no promises.

**Comment by filevans** [comment]
Hello, did you have any chance to look at Pro Race Driver / Toca Pro Race Driver to see if it could be patched to 480p? It's the only game that can't be forced with the generic codes. Thank you

**Comment by Rocky5** [comment]
> Hello, did you have any chance to look at Pro Race Driver / Toca Pro Race Driver to see if it could be patched to 480p? It's the only game that can't be forced with the generic codes. Thank you

I just did there, cant find anything in the xbe. Doesn't seem to use the same D3Device as other games that have patches.

Changed some values and got a hard crash with one lol
