### ISSUE TITLE
Xbmc emustation Question

### ISSUE THREAD

**Issue by Davidrsf** [Rocky5/XBMC-Emustation#72]
Hi Rocky, I have an xbox version 1.6 with modchip, I'm using xbmc4gamers as the main dashbord, I used the shortcut 2.0 for that, I use the emustation as an app but when I leave the game it goes back to xbmc4gamers, is there any way to get back to the emustation ? thanks in advance!

**Comment by Rocky5** [comment]
Not really the place to ask. But you have 2 options.

use my dashloader and enable “enable reload emustation after game/rom” under UI Settings menu. (Start button)

or

set Emustation as your default dashboard.

you need my dashloader to use the return function as I check and reload the dashboard. You can grab the hardmod version in my softmod GitHub under the xtras disc folder.

**Comment by calebTree** [comment]
I'm not confident with properly setting up the hardmod dashloader. Is the setup procedure to clone the repo then FTP the `dashloader` directory and `evodash.xbe` file over to the `C:\` drive?
I have the XBOX setup as a hardmod using [OGXbox Installer 2021](https://www.ogxbox.com/forums/index.php?/topic/4407-ogxbox-installer-2021/) which already came with a `dashloader` directory and the `ind-bios.cfg` file on the `C:\` drive. I am booting ind-bios.
When I enable "reload emustation" under UI settings, the ROMs fail to load. Attempting to launch a ROM returns "error". Disabling the "reload emustation" feature restores successful ROM launching. I would like to enable this feature.

**Comment by Rocky5** [comment]
Make sure the CACHE folder is on the root of E

**Comment by calebTree** [comment]
> Make sure the CACHE folder is on the root of E

Yes, a CACHE folder on the root of E allowed ROMs to launch with the "reload emustation" feature enabled. I am brought back to the default dash after exiting however.

**Comment by Rocky5** [comment]
> > Make sure the CACHE folder is on the root of E
> 
> Yes, a CACHE folder on the root of E allowed ROMs to launch with the "reload emustation" feature enabled. I am brought back to the default dash after exiting a ROM, however.

Get the script error and then grab the xbmc.log from the system folder and paste it to pastebin.com so I can see what’s happening.

**Comment by calebTree** [comment]
I haven't noticed a script error. I can give you the log. https://pastebin.com/6k2d6AHb

**Comment by Rocky5** [comment]
> I haven't noticed a script error. I can give you the log. https://pastebin.com/6k2d6AHb
> The last steps I did was start Emustation, load a ROM, then attempt to exit the ROM and expected to be brought back to Emustation only was brought back to default dash.

Nothing in that log file to see. 

Download this, https://github.com/Rocky5/Xbox-Softmodding-Tool/raw/5a7bfa1a2b6d6d33fc94689b16d67e51b31c9309/Extras%20Disc/Hardmod/dashloader/evoxdash.xbe

replace your current dashloader and let me know how it goes.
