### ISSUE TITLE
Themes question

### ISSUE THREAD

**Issue by loggio** [Rocky5/XBMC-Emustation#73]
I am going to modify the skin to be more usable on smaller 4:3 crt monitors/TV's as this is what I use my xbox on.

This will mean I'll need to enlarge a lot of the list controls, text and images so that they are more pleasing as currently a lot of the text is unreadable on smaller screens.

Trying to plan the best approach for this.

Question;
Since you have removed the option to change the skin through xbmc, it looks like the best approach would be to make a theme for the current skin like you have with the downloadable themes.

But this may limit my options... 

In the layouts folder for a theme, can I add layouts for any window? Like settings.xml and your custom.xml files for example?

This will allow me to modify all/any windows I need, without the need to modify the base skin... Other than maybe adding a few more lines to the "includes.xml" if needed.

Otherwise I may have to heavily modify the default skin... Which id like to avoid unless I have the option to change skins in xbmc settings.

I'd like to be able to share this with you so that others can download it from within xbmc-emustation.

Any advise you can give would be great!

Cheers,

Glen.

**Comment by Rocky5** [comment]
Currently no, but if you edit the default simple skin (xmls) I will see about making it change to use the 4:3 version if using SD resolutions. It’s been a long time since I looked at the hack job I done lol 

I cant remember if when changing the folder 720p to xml I stopped the ntsc or pal folders from working. If not then it’s as simple as making a ntsc folder and putting all the xml files from the xml folder int here and start editing away.

**Comment by Rocky5** [comment]
Ok had a look I never, so you can just make a new folder in side the simple folder and it should be used when a SD resolution is detected. 

CStdString CSkinInfo::GetDirFromRes(RESOLUTION res) const
{
  CStdString strRes;
  switch (res)
  {
  case PAL_4x3:
    strRes = "PAL";
    break;
  case PAL_16x9:
    strRes = "PAL16x9";
    break;
  case NTSC_4x3:
  case HDTV_480p_4x3:
    strRes = "NTSC";
    break;
  case NTSC_16x9:
  case HDTV_480p_16x9:
    strRes = "ntsc16x9";
    break;
  case HDTV_720p:
    strRes = "xml";
    break;
  case HDTV_1080i:
    strRes = "1080i";
    break;
  case INVALID:
  default:
    strRes = "";
    break;
  }
  return strRes;
}

**Comment by Rocky5** [comment]
Only thing is themes will need to be edited for 4:3 but I can host those on the downloader and make the edits to the scripts so they know what resolution we are running etc…

**Comment by loggio** [comment]
Nice, i will look into it. How would I handle the "layouts" folder for emulator windows? wouldn't changing those change for all resolutions?

**Comment by Rocky5** [comment]
> Nice, i will look into it. How would I handle the "layouts" folder for emulator windows? wouldn't changing those change for all resolutions?

I will sort that once you do the 4:3 stuff. You just fix everything to work at 3:4 I will do the backend stuff to make it all work. 
(I can check if we are in specific resolutions so I know what layout file to use)

**Comment by loggio** [comment]
Sounds good. 
I'm running in to an issue i need your help with, it's probably something to do with the scripts... Maybe Menu_Loader 
if i create a PAL folder for the skin and then select a system in the menu then it will always display same game list no mater what system i select..  doesn't happen with PORTS or XBOX or OPTIONS etc... only emulators.  

You should be able to test this by making a copy of the XML folder and renaming it to PAL and then set your resolution to PAL, then try opening different systems from the main menu.

if you switch back to xml folder resolution then it restores functionality.

I don't want to modify your script and potentially break something else...

**Comment by Rocky5** [comment]
> Sounds good. I'm running in to an issue i need your help with, it's probably something to do with the scripts... Maybe Menu_Loader if i create a PAL folder for the skin and then select a system in the menu then it will always display same game list no mater what system i select.. doesn't happen with PORTS or XBOX or OPTIONS etc... only emulators.
> 
> You should be able to test this by making a copy of the XML folder and renaming it to PAL and then set your resolution to PAL, then try opening different systems from the main menu.
> 
> if you switch back to xml folder resolution then it restores functionality.
> 
> I don't want to modify your script and potentially break something else...

Just edit the files in the Xbox folder, once done send them to me and I can add them correctly so everything works.

**Comment by loggio** [comment]
This does not work. 

* I have copied all the files from XML into a separate folder called PAL and began editing.
* I renamed xml to xmlbak so that it only looks at the PAL folder. 
* I have my resolution set to PAL 4:3
* Everything looks great at this stage.
* If i rename the PAL folder to back to xml and then restart emustation, the textures are all shrunk , pushed in the corner of the screen and look terrible.

seems xbmc is treating the xml and PAL folders differently with resolutions.

* if i edit the xml folder directly and enlarge certain texts etc... and then rename the folder to PAL everything is way oversized.


So i'm kind of stuck at this point as i can't skin any emulator windows until the scripts accept the PAL/NTSC folders.

**Comment by Rocky5** [comment]
> This does not work.
> 
> * I have copied all the files from XML into a separate folder called PAL and began editing.
> * I renamed xml to xmlbak so that it only looks at the PAL folder.
> * I have my resolution set to PAL 4:3
> * Everything looks great at this stage.
> * If i rename the PAL folder to back to xml and then restart emustation, the textures are all shrunk , pushed in the corner of the screen and look terrible.
> 
> seems xbmc is treating the xml and PAL folders differently with resolutions.
> 
> * if i edit the xml folder directly and enlarge certain texts etc... and then rename the folder to PAL everything is way oversized.
> 
> So i'm kind of stuck at this point as i can't skin any emulator windows until the scripts accept the PAL/NTSC folders.

Use this, just overwrite the files and rename your PAL folder to xml_sd
https://drive.google.com/file/d/12fQdFbKidC2CI95vJYTN4iDaDQf1geBj/view?usp=sharing

**Comment by loggio** [comment]
Trying to download says i need to request access. Have done so with my gmail account.

**Comment by Rocky5** [comment]
> Trying to download says i need to request access. Have done so with my gmail account.

Fixed sorry

**Comment by loggio** [comment]
awesome, that seems to behave properly now.  Thanks!

**Comment by loggio** [comment]
Hi Rocky5,
Hope all is well. See below link for my modifications to the simple theme for the SD resolution. 
I modified this using my PAL 720x576 14" commodore 1702 monitor. I only have 14" commodore monitors at home so i really can't test this on anything else.

I believe all windows have been modified and some scripts... can't remember which ones, probably menuloader.py as it generates the XML, overriding the jumplist.xml when it runs. There may be some dialog windows that need adjusting... things like the scanner etc...  There's a lot i had to do and was back and forth on this for months making slight tweaks. 

not sure if you have a way to test this? 

URL downloader... i modified as much as i could, but the script has stopped working for me as when i click "download" on an item it just sits there "loading" until i cancel.

I'm sure this is because my version of xbmc-emustation is out of date or the URLDownloader is out of date. But i can't really update it as i would have lost all my changes. and plus, you made me a modified version of the .xbe to work with the xml_sd folder. But if you end up merging this into the main download then that would be awesome.

https://drive.google.com/file/d/1Cm0tnlpcvd498fTBhCnjHDA8ULynG3ee/view?usp=sharing

**Comment by loggio** [comment]
I just tried the files that i sent you on a fresh install using xemu xbox emulator on PC and couldn't get the theme to work. it would just load default theme no matter what i did. 

Please use the below link instead. 
install xbmc-emustation as a separate app and just override using these files... hopefully that works for you. 

If you use xemu on windows, then use this setup:
AV Pack as = S-video
Display, Window size = 640x480

Then use enigmah .xbe to change the system to PAL 


https://drive.google.com/file/d/1jPFRE6pIwd9DoJdKUpHTc5D-qhPLeaj8/view?usp=sharing

**Comment by loggio** [comment]
also, just updated some dialogs. 
keyboard, filebrowser, numeric, networksetup 

https://drive.google.com/file/d/1myitiDoO7QFPCyGPh9ozZ5xuDg1Jf3C8/view?usp=sharing
