### ISSUE TITLE
simplified mode

### ISSUE THREAD

**Issue by XBOXLOVER6** [Rocky5/XBMC-Emustation#74]
hello 

could you tell me how to get out of the simplified mode?

thanks you

**Comment by Rocky5** [comment]
You mean kiosk mode?

KIOSK MODE: l
To unlock and return to the full UI, enter this code:
BLACK,UP,UP,DOWN,DOWN,LEFT,LEFT,RIGHT,RIGHT & A

**Comment by XBOXLOVER6** [comment]
thx for help , i've tried your hotkeys and nothing ..

this mode 
![image](https://user-images.githubusercontent.com/113383482/189733957-543b0faa-082a-4a4a-ba74-da9263ae7111.png)

**Comment by XBOXLOVER6** [comment]
problem of sight it is ok 
thank you

**Comment by XBOXLOVER6** [comment]
et au passage felicitations et merci for this creation
