### ISSUE TITLE
Issue scanning systems for roms

### ISSUE THREAD

**Issue by dmg9626** [Rocky5/XBMC-Emustation#75]
Hello,

I've just installed XBMC-Emustation on my xbox, following along with the README.me (cloning the repo and building from source, latest at master branch). 

I managed to launch into XBMC-Emustation, but selecting the Scan All Systems option in the Scanner menu results in a ... loading indicator in the top-left screen corner that continues running indefinitely (until I press B). Trying to select Manual Update Systems gives the same result. So as is I can't play any roms on a fresh install.

Possibly related: when running the `Build XBMC-Emustation.bat` script to build from source, I noticed that there's no roms folder created in the resulting `XBMC-Emustation\emustation\` directory. To work around this, I tried creating a `\roms\snes\` directory in `emustation` and placing a copy of Chrono Trigger in there, but it wasn't picked up by the above steps to scan for roms.

Maybe there's something wrong with either the build procedure or the options available under the Scanner menu? While poking through the change history, I found [this change](https://github.com/Rocky5/XBMC-Emustation/commit/f450f614a1b115bd4afbb43832a6cc78485f43b3) that fixed a bug where the initial setup wouldn't construct a \roms\ directory tree. I haven't had time to dig down this path to see if a regression caused this to fail again, so I figured I'd post here first in case anyone else has run into this issue.

Thanks in advance!

**Comment by Rocky5** [comment]
There is no need to build the source, you can always grab the latest prebuilt version. 

But if you want to build the source you need put a clean copy of XBMC 3.5.3 named XBMC next to the bat files and then run the build XBMC-Emustation.bat
