### ISSUE TITLE
Support scanning of CHD files for PSX games

### ISSUE THREAD

**Issue by DanoG74** [Rocky5/XBMC-Emustation#76]
Hi Rocky5.

Have been spending a few weeks setting up and customizing Emustation. Pretty awesome work over the years you've dedicated to this. I've gotten a very good handle on your work being a veteran to all things XBMC and Kodi for many many years.

My question is with scanning PSX files. I have found a fork of the PcXbox emulator (Pcsxbox_Tabajara02_biuld), that supports compressed CHD files and works very well. Using it in Emustation works great.

From my research, your scanner doesn't support adding CHD files to the emulator list correct?

I guess my request is, can you add CHD file extension support on scanning? Or, can you let me know where I can add this on the back end somehow so I can at least have Emustation know that there are roms available?

Thanks!

**Comment by Rocky5** [comment]
Add and new emu added to the downloader for it.
