### ISSUE TITLE
SD PAL simple theme

### ISSUE THREAD

**Issue by loggio** [Rocky5/XBMC-Emustation#77]
reference to original ticket: https://github.com/Rocky5/XBMC-Emustation/issues/73

Hi Rocky5, not sure if you see updates on "closed" tickets... so i'll create a new one. 

Hope all is well. See below link for my modifications to the simple theme for the SD resolution.
I modified this using my PAL 720x576 14" commodore 1702 monitor. I only have 14" commodore monitors at home so i really can't test this on anything else.

I believe all windows have been modified and some scripts... can't remember which ones, probably menuloader.py as it generates the XML, overriding the jumplist.xml when it runs. There may be some dialog windows that need adjusting... things like the scanner etc... There's a lot i had to do and was back and forth on this for months making slight tweaks.

not sure if you have a way to test this?

URL downloader... i modified as much as i could, but the script has stopped working for me as when i click "download" on an item it just sits there "loading" until i cancel.

I'm sure this is because my version of xbmc-emustation is out of date or the URLDownloader is out of date. But i can't really update it as i would have lost all my changes. and plus, you made me a modified version of the .xbe to work with the xml_sd folder. But if you end up merging this into the main download then that would be awesome.

https://drive.google.com/file/d/1Cm0tnlpcvd498fTBhCnjHDA8ULynG3ee/view?usp=sharing

**Comment by Rocky5** [comment]
I do see updates in closed tickets.

I will give this a whirl later today. Thank you.

**Comment by Rocky5** [comment]
OK been testing this and you seem to have combined the carbon theme with the simple theme :/ and for some reason I cant get any menu to look correct.

**Comment by Rocky5** [comment]
yeah you used theme files to build the skin, s now dialogs have the wrong colour etc... :/

**Comment by loggio** [comment]
Hmm okay bugger. I experimented with colours etc. early on and can't remember what I did exactly... Colours were changed to dark for less strain on CRT tubes as brighter / higher contrast images can blow out and blur/ghost the image. I think the carbon background  worked better in this case.

I think I was under the impression that anything inside the xml_sd folder would have no affect on standard xml folder as when changing resolutions to HD would use xml folder...

**Comment by Rocky5** [comment]
> Hmm okay bugger. I experimented with colours etc. early on and can't remember what I did exactly... Colours were changed to dark for less strain on CRT tubes as brighter / higher contrast images can blow out and blur/ghost the image. I think the carbon background worked better in this case.
> 
> I think I was under the impression that anything inside the xml_sd folder would have no affect on standard xml folder as when changing resolutions to HD would use xml folder...

The way it works is all themes use the simple xml files. Colours are controlled via the colours.xml

So you changing all the values inside the simple xml files will break all themes, and I can’t use them now.

🙈

**Comment by Rocky5** [comment]
https://postimg.cc/gallery/YhvmG1k

This is how it looks vs how it should look, but colours are still off.

**Comment by Rocky5** [comment]
> Yeah okay, so...
> 
> If I edit simple xml files, it needs to be just size/resolution/coordinate changes only?
> 
> Themes will control colour/backgrounds/layouts
> 
> Not at my computer right now so can't check... What about text sizing? Are font files controlled by themes?

Correct you just edit sizes and positions, nothing else :D

**Comment by loggio** [comment]
And fonts? Are font files in themes?

**Comment by loggio** [comment]
I guess don't sizing in Windows and dialogs can be changed in xml_sd as long as the font file is untouched as to not break anything.

**Comment by Rocky5** [comment]
> I guess font sizing in Windows and dialogs can be changed in xml_sd as long as the font file is untouched as to not break anything.

you edit the font.xml to change the sizes of fonts. That's in the sd folder.

**Comment by Rocky5** [comment]
Also please do the edits in NTSC mode, as it will scale to PAL. PAL doesn't scale to NTSC.

**Comment by Rocky5** [comment]
https://drive.google.com/file/d/18dYsowyfwY8D6GIXoBizYjmTpbwINMqt/view?usp=sharing

**Comment by loggio** [comment]
Ok. I will see how I go with NTSC resolution.

And some of the dialogs are controlled by scripts.... Jump list I think comes to mind.

Are you okay if I modify the script and you adapt it?

Or how should i handle that?

**Comment by Rocky5** [comment]
> Ok. I will see how I go with NTSC resolution.
> 
> And some of the dialogs are controlled by scripts.... Jump list I think comes to mind.
> 
> Are you okay if I modify the script and you adapt it?
> 
> Or how should i handle that?

I updated the scripts to work with the new folders. If there are other things that need tweaked let me know and I will make the changes.

**Comment by Rocky5** [comment]
OK i will update the script to use ntsc and pal sizes for the overlay.

**Comment by loggio** [comment]
> > Ok. I will see how I go with NTSC resolution.
> > And some of the dialogs are controlled by scripts.... Jump list I think comes to mind.
> > Are you okay if I modify the script and you adapt it?
> > Or how should i handle that?
> 
> I updated the scripts to work with the new folders. If there are other things that need tweaked let me know and I will make the changes.

Okay, thanks mate. Will have a play.

**Comment by loggio** [comment]
So, is there any way to use a "theme" to control overall colours? Or is it limited to 
Home/favs/emulator windows?

**Comment by Rocky5** [comment]
Just do the sizes for now and I will see about other things.

right now am taking the overlay menu form layouts out of the script so you can resize it independently.

**Comment by loggio** [comment]
Ok nice. Cheers

**Comment by Rocky5** [comment]
redownload the above zip added the files for the overlay in layouts and updated the script to use them.

**Comment by loggio** [comment]
you work fast. Thank you! 
I have limited spare time to work on this stuff so forgive me if it takes a while.

**Comment by loggio** [comment]
im curious about your workflow, what do you use to edit your xml files and how do you test the changes in real time?

**Comment by loggio** [comment]
ok, I have edited most of the dialogs and windows for both NTSC and PAL. everything is working okay, but I'm having issues with the "layouts/home" folder not working.

Anything i edit in that folder in relation to the home screen does not work. 

Tried also with carbon theme. Downloaded Carbon theme and added folder layouts/home/sd_ntsc/layout.xml
editing parameters in that file, reload xbmc... nothing changes. 

are you able to assist?

**Comment by Rocky5** [comment]
> ok, I have edited most of the dialogs and windows for both NTSC and PAL. everything is working okay, but I'm having issues with the "layouts/home" folder not working.
> 
> Anything i edit in that folder in relation to the home screen does not work.
> 
> Tried also with carbon theme. Downloaded Carbon theme and added folder layouts/home/sd_ntsc/layout.xml editing parameters in that file, reload xbmc... nothing changes.
> 
> are you able to assist?

Are you re-selecting the them after adding the sd_ntsc folder and layout file?

As the home screen is built only when you change theme. (I can make it just do it on every boot, I guess that would make more sense)

**Comment by Rocky5** [comment]
> im curious about your workflow, what do you use to edit your xml files and how do you test the changes in real time?

Sorry I missed this comment, I use Notepad++ to edit all my files.

**Comment by loggio** [comment]
Also noticed that label <autoscroll> control tags don't work in xbmc4xbox.

**Comment by loggio** [comment]
> 

hmm ok ... i'll test that.

**Comment by loggio** [comment]
I'll try reloading the theme after changes. give me a sec

**Comment by loggio** [comment]
reloading theme does nothing.

**Comment by Rocky5** [comment]
> I'll try reloading the theme after changes. give me a sec

Can you check the log when reloading theme, it will tell you if it’s SD NTSC Mode or SD PAL Mode.

as the script looks fine from what am looking at.

**Comment by loggio** [comment]
Previous line repeats 15 times.
17:48:41 M: 23887872 WARNING: CDVDPlayer::OnExit()
17:48:41 M: 23887872 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
17:48:41 M: 23887872  NOTICE: DVDPlayer: eof, waiting for queues to empty
17:48:41 M: 23887872  NOTICE: DVDPlayer: closing audio stream
17:48:41 M: 23887872  NOTICE: Closing audio stream
17:48:41 M: 23887872  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
17:48:41 M: 23887872  NOTICE: Waiting for audio thread to exit
17:48:41 M: 23887872  NOTICE: thread end: CDVDPlayerAudio::OnExit()
17:48:41 M: 24412160  NOTICE: Closing audio device
17:48:41 M: 24444928  NOTICE: Deleting audio codec
17:48:41 M: 24653824  NOTICE: DVDPlayer: closing video stream
17:48:41 M: 24653824  NOTICE: Closing video stream
17:48:42 M: 24653824  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
17:48:42 M: 24653824  NOTICE: waiting for video thread to exit
17:48:42 M: 24653824   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
17:48:42 M: 24653824  NOTICE: thread end: video_thread
17:48:42 M: 25178112  NOTICE: deleting video codec
17:48:42 M: 25657344  NOTICE: CDVDPlayer::OnExit() deleting demuxer
17:48:42 M: 25694208  NOTICE: CDVDPlayer::OnExit() deleting input stream
17:48:42 M: 26218496  NOTICE: CDVDPlayer::CloseFile()
17:48:42 M: 26218496 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:48:42 M: 26218496  NOTICE: DVDPlayer: waiting for threads to exit
17:48:42 M: 26218496  NOTICE: DVDPlayer: finished waiting
17:48:42 M: 26218496  NOTICE: CDVDPlayerVideo::~CDVDPlayerVideo - uninitting video device
17:49:54 M: 32116736   ERROR: CLocalizeStrings::ClearBlock: Trying to clear non existent block Q:\emustation\scripts
17:49:54 M: 35028992  NOTICE: Auto video playback script exited properly
17:52:01 M: 32215040  NOTICE: -->Python Initialized<--
17:52:05 M: 28385280  NOTICE: -->Python Initialized<--
17:52:05 M: 28762112  NOTICE: SD NTSC Mode
17:52:06 M: 37269504 WARNING: file doesnt have <fontset> with name 'simple.ttf', defaulting to first fontset
17:52:20 M: 35729408  NOTICE: -->Python Initialized<--
17:52:22 M: 45604864 WARNING: file doesnt have <fontset> with name 'simple.ttf', defaulting to first fontset
17:52:47 M: 41697280   ERROR: Keymapping error: no such action '-' defined
17:52:59 M: 35770368  NOTICE: -->Python Initialized<--
17:53:02 M: 31899648  NOTICE: -->Python Initialized<--
17:53:03 M: 33185792  NOTICE: SD NTSC Mode
17:53:03 M: 38236160 WARNING: file doesnt have <fontset> with name 'simple.ttf', defaulting to first fontset
17:53:04 M: 38309888   ERROR: Keymapping error: no such action '-' defined

**Comment by Rocky5** [comment]
Ok I know why 🙈

it’s adding it the xml/home.xml file 😂

ok will fix this later on, or you can edit the home_themer.py and change the “Home_XML_Path		= xbmc.translatePath('special://skin/xml/Home.xml')” line to point to the xml_sd_ntsc folder.

**Comment by loggio** [comment]
awesome! cheers, i can edit that myself. I'll let you know if i have further issues.

**Comment by loggio** [comment]
Also noticed that label autoscroll control tags don't work in xbmc4xbox. any workaround for this ? or a bug with xbmc? 

the publisher info in emulators view doesn't autoscroll even though the tags are set too. I need to adjust this to fit SD screen limitations and can't get it to scroll when text is cut off. 

autoscroll works for textbox... so for now my workaround is to modify it to a textbox and have wraparound labels. then have the textbox scroll vertical after 5seconds

**Comment by Rocky5** [comment]
> Also noticed that label autoscroll control tags don't work in xbmc4xbox. any workaround for this ? or a bug with xbmc?
> 
> the publisher info in emulators view doesn't autoscroll even though the autoscroll tag is there. I need to adjust this to fit SD screen limitations and can't get it to scroll when text is cut off.
> 
> autoscroll works for textbox... so for now my workaround is to modify it to a textbox and have wraparound labels. then have the textbox scroll vertical after 5seconds

A will need to take a look, but auto scroll should work on labels.

<scroll>true</scroll>

**Comment by loggio** [comment]
setting "scroll" to true works. but using <autoscroll< with a time delay and condition does nothing 

autoscroll delay="10000" time="1000" repeat="10000" condition="Container(9000).HasFocus"

**Comment by Rocky5** [comment]
> setting "scroll" to true works. but using <autoscroll< with a time delay and condition does nothing
> 
> autoscroll delay="10000" time="1000" repeat="10000" condition="Container(9000).HasFocus"

That’s only for the textbox control. We get no control over labels scroll delay for labels.

**Comment by loggio** [comment]
yeah, reading through the skinning manual i can see that. looks like you were experimenting because it's in your code. 

All good. textbox workaround seems to be ok for this.

**Comment by loggio** [comment]
Okay, ran into another problem. When in XBOX view and select "xbe edit mode" i get taken to a blank screen. 
I have appropriate xml files in = layouts/default/sd_ntsc/XBE files and they work when viewing applications.

might it be something in the menu_loader script?

**Comment by Rocky5** [comment]
> Okay, ran into another problem. When in XBOX view and select "xbe edit mode" i get taken to a blank screen. I have appropriate xml files in = layouts/default/sd_ntsc/XBE files and they work when viewing applications.
> 
> might it be something in the menu_loader script?

I got a new PC, so spend yesterday getting it all up and running. I fixed all previous issues and made it generate the home.xml on reload of emustation. (So any update to a layout file, set the theme again or reload emustation.

I will take a look at xbe menu not being themed in sd mode and get back to you later on in the day.

**Comment by loggio** [comment]
Please see link : https://drive.google.com/file/d/1Zo14UdnxhDkQH9gNtnt5CcMpLxqv_Egx/view?usp=sharing

Will obviously need all the patches that you shared with me for these to work properly. 

Calibrate screen so triangle sides meet edges of screen and center box is at 1.000

**Comment by Rocky5** [comment]
> Please see link : https://drive.google.com/file/d/1Zo14UdnxhDkQH9gNtnt5CcMpLxqv_Egx/view?usp=sharing
> 
> Will obviously need all the patches that you shared with me for these to work properly.
> 
> Calibrate screen so triangle sides meet edges of screen and center box is at 1.000

Thank you, I updated the google drive link with the new xbe and updated scripts. 

If you fixed the xbe menu loading above I wouldn’t overwrite the xml files. 

But I can’t test right now, if you’re able to see how loading is while booting emustation as I build the home menu on every load now. (It’s not noticeable on mine)

**Comment by loggio** [comment]
> > Please see link : https://drive.google.com/file/d/1Zo14UdnxhDkQH9gNtnt5CcMpLxqv_Egx/view?usp=sharing
> > Will obviously need all the patches that you shared with me for these to work properly.
> > Calibrate screen so triangle sides meet edges of screen and center box is at 1.000
> 
> Thank you, I updated the google drive link with the new xbe and updated scripts.
> 
> If you fixed the xbe menu loading above I wouldn’t overwrite the xml files.
> 
> But I can’t test right now, if you’re able to see how loading is while booting emustation as I build the home menu on every load now. (It’s not noticeable on mine)

seems to work ok.

one issue i did notice...
 if i switch to PAL and change theme to carbon, the theme changes but the carbon carousel backgrounds are not visible. 
switch back to NTSC and i can see them.  So haven't been able to edit the includes carousel backgrounds file for carbon backgrounds under PAL.

**Comment by Rocky5** [comment]
> > > Please see link : https://drive.google.com/file/d/1Zo14UdnxhDkQH9gNtnt5CcMpLxqv_Egx/view?usp=sharing
> > > Will obviously need all the patches that you shared with me for these to work properly.
> > > Calibrate screen so triangle sides meet edges of screen and center box is at 1.000
> > 
> > 
> > Thank you, I updated the google drive link with the new xbe and updated scripts.
> > If you fixed the xbe menu loading above I wouldn’t overwrite the xml files.
> > But I can’t test right now, if you’re able to see how loading is while booting emustation as I build the home menu on every load now. (It’s not noticeable on mine)
> 
> seems to work ok.
> 
> one issue i did notice... if i switch to PAL and change theme to carbon, the theme changes but the carbon carousel backgrounds are not visible. switch back to NTSC and i can see them. So haven't been able to edit the includes carousel backgrounds file for carbon backgrounds under PAL.

So we good to go with your files?


If you’re able to fix the Pal carbon issue that would be great as it’s a little more difficult for me and I have so much other crap am trying to do 😂🙈

am losing track, hence the late reply. Sorry.

**Comment by loggio** [comment]
> > > > Please see link : https://drive.google.com/file/d/1Zo14UdnxhDkQH9gNtnt5CcMpLxqv_Egx/view?usp=sharing
> > > > Will obviously need all the patches that you shared with me for these to work properly.
> > > > Calibrate screen so triangle sides meet edges of screen and center box is at 1.000
> > > 
> > > 
> > > Thank you, I updated the google drive link with the new xbe and updated scripts.
> > > If you fixed the xbe menu loading above I wouldn’t overwrite the xml files.
> > > But I can’t test right now, if you’re able to see how loading is while booting emustation as I build the home menu on every load now. (It’s not noticeable on mine)
> > 
> > 
> > seems to work ok.
> > one issue i did notice... if i switch to PAL and change theme to carbon, the theme changes but the carbon carousel backgrounds are not visible. switch back to NTSC and i can see them. So haven't been able to edit the includes carousel backgrounds file for carbon backgrounds under PAL.
> 
> So we good to go with your files?
> 
> If you’re able to fix the Pal carbon issue that would be great as it’s a little more difficult for me and I have so much other crap am trying to do 😂🙈
> 
> am losing track, hence the late reply. Sorry.

I think the files are good to go. I'll try fix the carbon backdrops over next couple of weeks when I have time. not too sure if it's a script or xml thing. considering both NTSC and PAL XML are the same, only difference being height and y coordinate adjustments I'm leaning towards a script thing.

**Comment by Rocky5** [comment]
> > > > > Please see link : https://drive.google.com/file/d/1Zo14UdnxhDkQH9gNtnt5CcMpLxqv_Egx/view?usp=sharing
> > > > > Will obviously need all the patches that you shared with me for these to work properly.
> > > > > Calibrate screen so triangle sides meet edges of screen and center box is at 1.000
> > > > 
> > > > 
> > > > Thank you, I updated the google drive link with the new xbe and updated scripts.
> > > > If you fixed the xbe menu loading above I wouldn’t overwrite the xml files.
> > > > But I can’t test right now, if you’re able to see how loading is while booting emustation as I build the home menu on every load now. (It’s not noticeable on mine)
> > > 
> > > 
> > > seems to work ok.
> > > one issue i did notice... if i switch to PAL and change theme to carbon, the theme changes but the carbon carousel backgrounds are not visible. switch back to NTSC and i can see them. So haven't been able to edit the includes carousel backgrounds file for carbon backgrounds under PAL.
> > 
> > 
> > So we good to go with your files?
> > If you’re able to fix the Pal carbon issue that would be great as it’s a little more difficult for me and I have so much other crap am trying to do 😂🙈
> > am losing track, hence the late reply. Sorry.
> 
> I think the files are good to go. I'll try fix the carbon backdrops over next couple of weeks when I have time. not too sure if it's a script or xml thing. considering both NTSC and PAL XML are the same, only difference being height and y coordinate adjustments I'm leaning towards a script thing.

Carbons theme files will need to be updated for it to work.

each theme will needs its files updated for SD resolutions. The above zip only has simple done.

**Comment by loggio** [comment]
yeah, i did all that. The carbon backgound icons use the "includes_backgrounds.xml" .
Not in front of my home computer at the moment so i'll have to check when i'm home

**Comment by loggio** [comment]
Do you want me to update all the themes as well ?

**Comment by Rocky5** [comment]
> yeah, i did all that. The carbon backgound icons use the "includes_backgrounds.xml" . Not in front of my home computer at the moment so i'll have to check when i'm home
> 
> haven't done anything but simple, only reason i tried with carbon is because the background code is in that include.xml

Yeah each theme uses its own code basically to do its layout. 

What I may do is make the common stuff be part of the main xmls and just <include> them in the themes. As I can still move stuff about etc…

Leave with me and I will see what I can do. (This will make updating parts of themes a lot simpler

**Comment by loggio** [comment]
> > yeah, i did all that. The carbon backgound icons use the "includes_backgrounds.xml" . Not in front of my home computer at the moment so i'll have to check when i'm home
> > haven't done anything but simple, only reason i tried with carbon is because the background code is in that include.xml
> 
> Yeah each theme uses its own code basically to do its layout.
> 
> What I may do is make the common stuff be part of the main xmls and just <“include”> them in the themes. As I can still move stuff about etc…
> 
> Leave with me and I will see what I can do. (This will make updating parts of themes a lot simpler

That's a good approach. 

Includes can always be ignored if a user wants a more "customised" theme.

**Comment by loggio** [comment]
ok, lol sorry... it was me, when i was testing, i forgot to change the home_themer script to point to "sd_pal" folder as you mentioned above... so, yeah.... was never going to work. just testing it now though, I need to resize the carbon carousel backgrounds for NTSC and PAL in the includes xml as they're a bit small, so i'll do that now and send it through

**Comment by loggio** [comment]
ok, download simple theme here: 
https://drive.google.com/file/d/1L5DAAvMiWdHnn74wsxl__FBNgDLq1QMF/view?usp=sharing

carbon backgrounds are working now. As stated earlier, I have only modified the simple theme and its layouts for NTSC and PAL. All other themes will need to be updated for PAL and NTSC.

But if you want me to help with that then just let me know, I can chip away at it.

**Comment by loggio** [comment]
Hey, hope you're doing well!

Just wondering if you have plans to include this?

**Comment by Rocky5** [comment]
> Hey, hope you're doing well!
> 
> Just wondering if you have plans to include this?

I do yes, I haven’t touched Xbox stuff in a while, life’s been in the road.

I need to adjust a couple more script to not let people choose themes that don’t support SD resolutions. 

Leave it with me and I will get to it over the weekend. It will be a test build of emustation on the downloader.

**Comment by Rocky5** [comment]
@loggio added all the SD stuff to the text build. Downloader works with it all also and I fixed all issues I found. 

Let me know how it works 🙏

**Comment by loggio** [comment]
Sorry about late reply. Been very busy.

Just tested this and it's working great so far.
I'll let you know if I run into any major issues.

Changelog window was oversized and unreadable. If possible might be worth looking into having the changelog text as a separate file so that you don't need to update sd and hd changelog dialogs every time. 

All other themes need updating. But you already know that.

 downloader is working fine
