### ISSUE TITLE
context menu not showing

### ISSUE THREAD

**Issue by nik2208** [Rocky5/XBMC-Emustation#78]
I've just installed the latest versione and the menu is in a clickable empty list, so you don't know what you're doing

**Comment by Rocky5** [comment]
If you installed the test build, this ain’t the place to discuss it. This place is for the current code in on this gif that is working. 

You want to discuss things regarding test builds that are going to have issues, hence the name test build. Discuss it on discord, Reddit or OGXbox forums.

**Comment by nik2208** [comment]
Sorry maybe I'm missing something I'm on master and followed the instructions on the MD file. How do I know if it is the test or the stable build?

**Comment by Rocky5** [comment]
> Sorry maybe I'm missing something I'm on master and followed the instructions on the MD file. How do I know if it is the test or the stable build?

Download the prebuilt version from the download link in the md file. 

Different systems do different things when build the source (running the .bat files)

**Comment by Rocky5** [comment]
Or if you can record me a video and upload it somewhere showing me the issue that will help 10 fold 😁

**Comment by nik2208** [comment]
![1673271401333772382914902575407](https://user-images.githubusercontent.com/28157038/211320954-5181b83c-d6d6-44a0-a84b-9ac232d4b068.jpg)
This is what happens playing start

**Comment by Rocky5** [comment]
> ![1673271401333772382914902575407](https://user-images.githubusercontent.com/28157038/211320954-5181b83c-d6d6-44a0-a84b-9ac232d4b068.jpg)
> This is what happens playing start

Looks like the fonts missing, is it just the start menu that’s like that? (As nothings changed code wise in this menu for years 😂)

load up emustation, press start
FTP in and goto Q:\system\ you will see xbmc.log. 
send me this file please. 

Also make sure your FTP programs transfer mode is set to binary. (FileZilla, has a habit of corrupting files if it’s left as auto)

**Comment by nik2208** [comment]
ok putting filezilla into binary transfer solved the issue ;)
