### ISSUE TITLE
Xbox Artwork Installer crashes if game folder ends with underscore_

### ISSUE THREAD

**Issue by SNWRbxT** [Rocky5/XBMC-Emustation#8]
Title says it all - but if your games are named like:
G:\Games\Spongebob_Squarepants_Battle_For_Bikini_
G:\Games\Star_Wars_Knights_Of_The_Old_Republic_2_

Then it will crash.

I solved this by using double underscore instead:
tempname = Game_Folder_Full_Path_Alt[:-2]+"__"
Inside of the default.py of the installer script, but you might want to come up with a better solution.

**Comment by Rocky5** [comment]
Cheers, strange way of naming folders but I will fix it up and update the installer in the downloader. 
( probably tomorrow night UK time it will be fixed )
