### ISSUE TITLE
Scanning roms

### ISSUE THREAD

**Issue by Knehall1** [Rocky5/XBMC-Emustation#80]
I am having an issue scanning roms. Emulators affected are sega cd, turbo grafx 16 cd, pc engine cd, mame,fbl, and n64. Now all these were worki g without a hitch. I started with emustaion 1.2 then upgraded to 1.3 then on to 1.4. I did a full rescan of all roms about a week ago and it all went haywire. I keep getting errors and resan roms prompts. I upgraded to the test build with no luck and then downgraded back to the stable 1.4. I found a work around on the cd emulators by scanning the cue files first then ftp'ing over the rest of the files afterwards. The other ones seem to be a lost cause. Any help is appreciated 🙏

**Comment by Rocky5** [comment]
I need a log, E:\TDATA\Rocky5 needs these\

**Comment by Knehall1** [comment]
02:08:33 M: 56766464  NOTICE:
-----------------------------------------------------------------------
02:08:33 M: 56745984  NOTICE: Starting XBMC4Xbox 3.6-DEV-r33042 (SVN:33042,
compiler 1310). Built on Dec 28 2022
02:08:33 M: 56745984  NOTICE: special://xbmc/ is mapped to: Q:\
02:08:33 M: 56745984  NOTICE: special://masterprofile/ is mapped to:
Q:\system\UserData
02:08:33 M: 56745984  NOTICE: special://home/ is mapped to: Q:\
02:08:33 M: 56745984  NOTICE: special://root/ is mapped to: E:\dashboard
02:08:33 M: 56745984  NOTICE: special://emustation_scripts/ is mapped to:
Q:\emustation\scripts\
02:08:33 M: 56745984  NOTICE: special://themes_root/ is mapped to:
Q:\emustation\themes\
02:08:33 M: 56745984  NOTICE: special://theme/ is mapped to: the currently
loaded theme
02:08:33 M: 56745984  NOTICE: special://urldownloader/ is mapped to:
Q:\emustation\scripts\urldownloader\
02:08:33 M: 56745984  NOTICE: special://temp/ is mapped to: Z:\
02:08:33 M: 56745984  NOTICE: The executable running is:
E:\dashboard\Default.xbe
02:08:33 M: 56745984  NOTICE: Log File is located: Q:\system\xbmc.log
02:08:33 M: 56745984  NOTICE:
-----------------------------------------------------------------------
02:08:33 M: 56745984  NOTICE: Unmapped drive T
02:08:33 M: 56745984  NOTICE: Mapping drive T to
Harddisk0\Partition1\dashboard\system\UserData\
02:08:33 M: 56745984  NOTICE: Setup DirectX
02:08:33 M: 56721408  NOTICE: Mapping drive C to Harddisk0\Partition2
02:08:33 M: 56717312  NOTICE: Mapping drive E to Harddisk0\Partition1
02:08:33 M: 56717312  NOTICE: Unmapped drive D
02:08:33 M: 56717312  NOTICE: Mapping drive D to Cdrom0
02:08:36 M: 56717312  NOTICE:   map extended drive F:
02:08:36 M: 56717312  NOTICE: Mapping drive F to Harddisk0\Partition6
02:08:39 M: 56717312  NOTICE:   map extended drive G:
02:08:39 M: 56717312  NOTICE: Mapping drive G to Harddisk0\Partition7
02:08:39 M: 56717312  NOTICE: Mapping drive X to Harddisk0\Partition3
02:08:39 M: 56717312  NOTICE: Mapping drive Y to Harddisk0\Partition4
02:08:39 M: 56717312  NOTICE: Unmapped drive Z
02:08:39 M: 56717312  NOTICE: Mapping drive Z to Harddisk0\Partition5
02:08:39 M: 56717312  NOTICE: load settings...
02:08:39 M: 56717312  NOTICE: Mapping drive P to
Harddisk0\Partition1\dashboard\system\UserData\
02:08:39 M: 56717312  NOTICE: Mapping drive S to
Harddisk0\Partition1\dashboard\emustation\themes\
02:08:39 M: 56717312  NOTICE: special://profile/ is mapped to:
special://masterprofile/
02:08:39 M: 56717312  NOTICE: loading
special://masterprofile/guisettings.xml
02:08:39 M: 56340480  NOTICE: Getting hardware information now...
02:08:39 M: 56340480  NOTICE: Checking resolution 10
02:08:39 M: 56340480  NOTICE: Setting autoresolution mode 4
02:08:39 M: 56340480  NOTICE: Loading player core factory settings from
special://xbmc/system/playercorefactory.xml.
02:08:39 M: 56315904  NOTICE: Loaded playercorefactory configuration
02:08:39 M: 56295424  NOTICE: Loading player core factory settings from
special://masterprofile/playercorefactory.xml.
02:08:39 M: 56295424  NOTICE: special://masterprofile/playercorefactory.xml
does not exist. Skipping.
02:08:39 M: 56295424  NOTICE: Loaded advancedsettings.xml from
special://profile/advancedsettings.xml
02:08:39 M: 56295424  NOTICE: Contents of
special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <powersave>false</powersave>
                                              <nodvdrom>false</nodvdrom>

<enableintro>true</enableintro>
                                              <splash>false</splash>
                                              <pictures>

<screenshotpath>Q:\system\Screenshots\</screenshotpath>
                                              </pictures>
                                            </advancedsettings>
02:08:39 M: 56295424  NOTICE: Getting hardware information now...
02:08:39 M: 56295424  NOTICE: Checking resolution 10
02:08:39 M: 56295424  NOTICE: Setting autoresolution mode 4
02:08:39 M: 56295424  NOTICE: Default Video Player: dvdplayer
02:08:39 M: 56295424  NOTICE: Default Audio Player: paplayer
02:08:39 M: 56295424  NOTICE: Per AV pack settings are off
02:08:39 M: 56619008  NOTICE: special://masterprofile/sources.xml
02:08:39 M: 50700288  NOTICE: Network: Using DHCP IP settings
02:08:39 M: 50384896  NOTICE: Not using idle thread with HLT (no power
saving)
02:08:39 M: 50384896  NOTICE: Checking the Date!
02:08:39 M: 50384896  NOTICE: start dvd mediatype detection
02:08:39 M: 50319360  NOTICE: initializing playlistplayer
02:08:39 M: 50319360  NOTICE: DONE initializing playlistplayer
02:08:39 M: 50311168  NOTICE: load simple skin:[simple]
02:08:41 M: 41324544  NOTICE: -->Python Initialized<--
02:08:42 M: 40030208  NOTICE: initialize done
02:08:42 M: 40058880  NOTICE: Running the application...
02:08:43 M: 33759232   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:08:43 M: 33759232   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:08:43 M: 37392384   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:08:43 M: 37388288   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:08:43 M: 37916672  NOTICE: start timeserver client
02:08:43 M: 37851136  NOTICE: XBFileZilla: Starting...
02:08:43 M: 36130816 WARNING: JpegIO: Error 55: Not a JPEG file: starts
with 0x%02x 0x%02x
02:08:45 M: 40235008  NOTICE: XBFileZilla: Started
02:08:48 M: 40251392   ERROR: Unable to wait for NTP reply from the SNTP
server, GetLastError returns 10060
02:23:29 M: 38739968   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:23:29 M: 38739968   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:23:29 M: 42315776   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:23:29 M: 42315776   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:23:29 M: 41058304 WARNING: JpegIO: Error 55: Not a JPEG file: starts
with 0x%02x 0x%02x
02:27:55 M: 42070016   ERROR: PICTURE: Error loading image
layouts/waterasupervision/art/system_art.png
02:28:04 M: 37371904  NOTICE: -->Python Initialized<--
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:06 M: 44179456   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:06 M: 44179456   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:06 M: 42356736   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\choukuukanking2 (1964x11-5.60).jpg
02:28:06 M: 42356736   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\choukuukanking2 (1964x11-5.60).jpg
02:28:10 M: 37167104  NOTICE: -->Python Initialized<--
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:12 M: 44167168   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:12 M: 44171264   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:12 M: 42389504   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\choukuukanking2 (1964x11-5.60).jpg
02:28:12 M: 42389504   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\choukuukanking2 (1964x11-5.60).jpg
02:28:16 M: 37535744  NOTICE: -->Python Initialized<--
02:28:30 M: 35573760   ERROR: Control 10 in window 10101 has been asked to
focus, but it can't
02:28:38 M: 35942400   ERROR: -->
------------------------------------------ <--
02:28:38 M: 35942400   ERROR: --> Python script returned the following
error <--
02:28:38 M: 35942400   ERROR: -->
------------------------------------------ <--
02:28:38 M: 35942400   ERROR: Error Type: <type 'exceptions.NameError'>
02:28:38 M: 35942400   ERROR: Error Contents: name 'Found_Roms' is not
defined
02:28:39 M: 35942400   ERROR: Traceback (most recent call last):
                                              File
"Q:\emustation\scripts\create_rom_lists.py", line 1508, in <module>
                                                if not
xbmc.getCondVisibility('Window.IsVisible(10000)') and Found_Roms == 1:
                                            NameError: name 'Found_Roms' is
not defined
02:28:39 M: 35942400   ERROR: --> --------------------------------- <--
02:28:39 M: 35942400   ERROR: --> End of Python script error report <--
02:28:39 M: 35942400   ERROR: --> --------------------------------- <--




02:08:33 M: 56766464  NOTICE:
-----------------------------------------------------------------------
02:08:33 M: 56745984  NOTICE: Starting XBMC4Xbox 3.6-DEV-r33042 (SVN:33042,
compiler 1310). Built on Dec 28 2022
02:08:33 M: 56745984  NOTICE: special://xbmc/ is mapped to: Q:\
02:08:33 M: 56745984  NOTICE: special://masterprofile/ is mapped to:
Q:\system\UserData
02:08:33 M: 56745984  NOTICE: special://home/ is mapped to: Q:\
02:08:33 M: 56745984  NOTICE: special://root/ is mapped to: E:\dashboard
02:08:33 M: 56745984  NOTICE: special://emustation_scripts/ is mapped to:
Q:\emustation\scripts\
02:08:33 M: 56745984  NOTICE: special://themes_root/ is mapped to:
Q:\emustation\themes\
02:08:33 M: 56745984  NOTICE: special://theme/ is mapped to: the currently
loaded theme
02:08:33 M: 56745984  NOTICE: special://urldownloader/ is mapped to:
Q:\emustation\scripts\urldownloader\
02:08:33 M: 56745984  NOTICE: special://temp/ is mapped to: Z:\
02:08:33 M: 56745984  NOTICE: The executable running is:
E:\dashboard\Default.xbe
02:08:33 M: 56745984  NOTICE: Log File is located: Q:\system\xbmc.log
02:08:33 M: 56745984  NOTICE:
-----------------------------------------------------------------------
02:08:33 M: 56745984  NOTICE: Unmapped drive T
02:08:33 M: 56745984  NOTICE: Mapping drive T to
Harddisk0\Partition1\dashboard\system\UserData\
02:08:33 M: 56745984  NOTICE: Setup DirectX
02:08:33 M: 56721408  NOTICE: Mapping drive C to Harddisk0\Partition2
02:08:33 M: 56717312  NOTICE: Mapping drive E to Harddisk0\Partition1
02:08:33 M: 56717312  NOTICE: Unmapped drive D
02:08:33 M: 56717312  NOTICE: Mapping drive D to Cdrom0
02:08:36 M: 56717312  NOTICE:   map extended drive F:
02:08:36 M: 56717312  NOTICE: Mapping drive F to Harddisk0\Partition6
02:08:39 M: 56717312  NOTICE:   map extended drive G:
02:08:39 M: 56717312  NOTICE: Mapping drive G to Harddisk0\Partition7
02:08:39 M: 56717312  NOTICE: Mapping drive X to Harddisk0\Partition3
02:08:39 M: 56717312  NOTICE: Mapping drive Y to Harddisk0\Partition4
02:08:39 M: 56717312  NOTICE: Unmapped drive Z
02:08:39 M: 56717312  NOTICE: Mapping drive Z to Harddisk0\Partition5
02:08:39 M: 56717312  NOTICE: load settings...
02:08:39 M: 56717312  NOTICE: Mapping drive P to
Harddisk0\Partition1\dashboard\system\UserData\
02:08:39 M: 56717312  NOTICE: Mapping drive S to
Harddisk0\Partition1\dashboard\emustation\themes\
02:08:39 M: 56717312  NOTICE: special://profile/ is mapped to:
special://masterprofile/
02:08:39 M: 56717312  NOTICE: loading
special://masterprofile/guisettings.xml
02:08:39 M: 56340480  NOTICE: Getting hardware information now...
02:08:39 M: 56340480  NOTICE: Checking resolution 10
02:08:39 M: 56340480  NOTICE: Setting autoresolution mode 4
02:08:39 M: 56340480  NOTICE: Loading player core factory settings from
special://xbmc/system/playercorefactory.xml.
02:08:39 M: 56315904  NOTICE: Loaded playercorefactory configuration
02:08:39 M: 56295424  NOTICE: Loading player core factory settings from
special://masterprofile/playercorefactory.xml.
02:08:39 M: 56295424  NOTICE: special://masterprofile/playercorefactory.xml
does not exist. Skipping.
02:08:39 M: 56295424  NOTICE: Loaded advancedsettings.xml from
special://profile/advancedsettings.xml
02:08:39 M: 56295424  NOTICE: Contents of
special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <powersave>false</powersave>
                                              <nodvdrom>false</nodvdrom>

<enableintro>true</enableintro>
                                              <splash>false</splash>
                                              <pictures>

<screenshotpath>Q:\system\Screenshots\</screenshotpath>
                                              </pictures>
                                            </advancedsettings>
02:08:39 M: 56295424  NOTICE: Getting hardware information now...
02:08:39 M: 56295424  NOTICE: Checking resolution 10
02:08:39 M: 56295424  NOTICE: Setting autoresolution mode 4
02:08:39 M: 56295424  NOTICE: Default Video Player: dvdplayer
02:08:39 M: 56295424  NOTICE: Default Audio Player: paplayer
02:08:39 M: 56295424  NOTICE: Per AV pack settings are off
02:08:39 M: 56619008  NOTICE: special://masterprofile/sources.xml
02:08:39 M: 50700288  NOTICE: Network: Using DHCP IP settings
02:08:39 M: 50384896  NOTICE: Not using idle thread with HLT (no power
saving)
02:08:39 M: 50384896  NOTICE: Checking the Date!
02:08:39 M: 50384896  NOTICE: start dvd mediatype detection
02:08:39 M: 50319360  NOTICE: initializing playlistplayer
02:08:39 M: 50319360  NOTICE: DONE initializing playlistplayer
02:08:39 M: 50311168  NOTICE: load simple skin:[simple]
02:08:41 M: 41324544  NOTICE: -->Python Initialized<--
02:08:42 M: 40030208  NOTICE: initialize done
02:08:42 M: 40058880  NOTICE: Running the application...
02:08:43 M: 33759232   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:08:43 M: 33759232   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:08:43 M: 37392384   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:08:43 M: 37388288   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:08:43 M: 37916672  NOTICE: start timeserver client
02:08:43 M: 37851136  NOTICE: XBFileZilla: Starting...
02:08:43 M: 36130816 WARNING: JpegIO: Error 55: Not a JPEG file: starts
with 0x%02x 0x%02x
02:08:45 M: 40235008  NOTICE: XBFileZilla: Started
02:08:48 M: 40251392   ERROR: Unable to wait for NTP reply from the SNTP
server, GetLastError returns 10060
02:23:29 M: 38739968   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:23:29 M: 38739968   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:23:29 M: 42315776   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:23:29 M: 42315776   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:23:29 M: 41058304 WARNING: JpegIO: Error 55: Not a JPEG file: starts
with 0x%02x 0x%02x
02:27:55 M: 42070016   ERROR: PICTURE: Error loading image
layouts/waterasupervision/art/system_art.png
02:28:04 M: 37371904  NOTICE: -->Python Initialized<--
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:06 M: 45035520   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:06 M: 44179456   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:06 M: 44179456   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:06 M: 42356736   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\choukuukanking2 (1964x11-5.60).jpg
02:28:06 M: 42356736   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\choukuukanking2 (1964x11-5.60).jpg
02:28:10 M: 37167104  NOTICE: -->Python Initialized<--
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:12 M: 45027328   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:12 M: 44167168   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:28:12 M: 44171264   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:28:12 M: 42389504   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\choukuukanking2 (1964x11-5.60).jpg
02:28:12 M: 42389504   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\choukuukanking2 (1964x11-5.60).jpg
02:28:16 M: 37535744  NOTICE: -->Python Initialized<--
02:28:30 M: 35573760   ERROR: Control 10 in window 10101 has been asked to
focus, but it can't
02:28:38 M: 35942400   ERROR: -->
------------------------------------------ <--
02:28:38 M: 35942400   ERROR: --> Python script returned the following
error <--
02:28:38 M: 35942400   ERROR: -->
------------------------------------------ <--
02:28:38 M: 35942400   ERROR: Error Type: <type 'exceptions.NameError'>
02:28:38 M: 35942400   ERROR: Error Contents: name 'Found_Roms' is not
defined
02:28:39 M: 35942400   ERROR: Traceback (most recent call last):
                                              File
"Q:\emustation\scripts\create_rom_lists.py", line 1508, in <module>
                                                if not
xbmc.getCondVisibility('Window.IsVisible(10000)') and Found_Roms == 1:
                                            NameError: name 'Found_Roms' is
not defined
02:28:39 M: 35942400   ERROR: --> --------------------------------- <--
02:28:39 M: 35942400   ERROR: --> End of Python script error report <--
02:28:39 M: 35942400   ERROR: --> --------------------------------- <--
02:28:48 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\clay fighter 63 (1964-5.60).jpg
02:28:48 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\clay fighter 63 (1964-5.60).jpg
02:28:48 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\clay fighter sc (pj64x14-5.10).jpg
02:28:48 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\clay fighter sc (pj64x14-5.10).jpg
02:28:49 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\conkers (pj64x14-6.11).jpg
02:28:49 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\conkers (pj64x14-6.11).jpg
02:28:49 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\cruis'n usa (1964-5.10).jpg
02:28:49 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\cruis'n usa (1964-5.10).jpg
02:28:49 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\cruis'n world (1964-5.10).jpg
02:28:49 M: 42209280   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\cruis'n world (1964-5.10).jpg
02:28:50 M: 42283008   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\donald duck (pj64x16-5.31).jpg
02:28:50 M: 42283008   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\donald duck (pj64x16-5.31).jpg
02:28:50 M: 42283008   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\doom 64 (1964x11-6.12).jpg
02:28:50 M: 42283008   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\doom 64 (1964x11-6.12).jpg
02:28:51 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\duke nukem (1964x11-6.12).jpg
02:28:51 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\duke nukem (1964x11-6.12).jpg
02:28:51 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\earthworm jim (1964x11-5.31).jpg
02:28:51 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\earthworm jim (1964x11-5.31).jpg
02:28:51 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\dukenukemzh (1964-6.12).jpg
02:28:51 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\dukenukemzh (1964-6.12).jpg
02:28:52 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\duke nukem (1964x11-6.12).jpg
02:28:52 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\duke nukem (1964x11-6.12).jpg
02:28:52 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\screenshots\doom 64 (1964x11-6.12).jpg
02:28:52 M: 42213376   ERROR: PICTURE: Error loading image
F:\Media\n64\boxart\doom 64 (1964x11-6.12).jpg
02:28:54 M: 37388288  NOTICE: -->Python Initialized<--
02:29:00 M: 37806080  NOTICE: -->Python Initialized<--
02:29:02 M: 44892160   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:29:02 M: 44892160   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:29:02 M: 44892160   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:29:02 M: 44892160   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:29:04 M: 37195776   ERROR: XFILE::CDirectory::GetDirectory - Error
getting Q:\system\plugins\programs
02:29:04 M: 37175296   ERROR: XFILE::CDirectory::GetDirectory - Error
getting special://home/system/plugins/programs
02:29:05 M: 35364864  NOTICE: -->Python Initialized<--
02:29:14 M: 35307520  NOTICE: -->Python Initialized<--
02:29:22 M: 32854016   ERROR: Control 10 in window 10101 has been asked to
focus, but it can't
02:31:19 M: 33210368   ERROR: -->
------------------------------------------ <--
02:31:19 M: 33210368   ERROR: --> Python script returned the following
error <--
02:31:19 M: 33210368   ERROR: -->
------------------------------------------ <--
02:31:19 M: 33210368   ERROR: Error Type: <type 'exceptions.NameError'>
02:31:19 M: 33210368   ERROR: Error Contents: name 'Found_Roms' is not
defined
02:31:19 M: 33210368   ERROR: Traceback (most recent call last):
                                              File
"Q:\emustation\scripts\create_rom_lists.py", line 1508, in <module>
                                                if not
xbmc.getCondVisibility('Window.IsVisible(10000)') and Found_Roms == 1:
                                            NameError: name 'Found_Roms' is
not defined
02:31:19 M: 33210368   ERROR: --> --------------------------------- <--
02:31:19 M: 33210368   ERROR: --> End of Python script error report <--
02:31:19 M: 33210368   ERROR: --> --------------------------------- <--

**Comment by Knehall1** [comment]
it is the earthworm james set......... 212 rom pack. ive tried 2
different sets downloaded from 2 different sources. i can run them from the
emulator fine, but not through the carousel. ive tried scanning both while
in the game list and while on the carousel.

fbl show a list of the games and artwork. wont show synopsis info or the
correct game titles. when i try to start a game the screen  goes black for
about 15 seconds then returns to the game list.

mame show the same as fbl but when i click on a game it tells me to rescan
my roms. ive tried to scan those both while in the game list and on the
carousel.

**Comment by Rocky5** [comment]
> it is the earthworm james set......... 212 rom pack. ive tried 2 different sets downloaded from 2 different sources. i can run them from the emulator fine, but not through the carousel. ive tried scanning both while in the game list and while on the carousel. fbl show a list of the games and artwork. wont show synopsis info or the correct game titles. when i try to start a game the screen goes black for about 15 seconds then returns to the game list. mame show the same as fbl but when i click on a game it tells me to rescan my roms. ive tried to scan those both while in the game list and on the carousel.
> […](#)

Make sure your paths are correct if using custom paths. Also do a full scan from the carousel and when you get an error or the script stops. Grab the log from Q:\system\

upload it to pastebin.com and paste the link here please. 

As what your describing shouldn’t be happening.

**Comment by Knehall1** [comment]
just finished full rom scan. scan did not stop. no error messages either.
still have same problems. fbl wont show synopsis or load a game. mame wont
show synopsis. mame and n64 give me a rescan roms message when selecting a
game to run.

**Comment by Rocky5** [comment]
> just finished full rom scan. scan did not stop. no error messages either. still have same problems. fbl wont show synopsis or load a game. mame wont show synopsis. mame and n64 give me a rescan roms message when selecting a game to run.
> […](#)

I still need the log after you do a scan. If it’s not loading systems it’s failed along the way somewhere.

**Comment by Knehall1** [comment]
https://pastebin.com/wwVKsjx6

**Comment by Rocky5** [comment]
> https://pastebin.com/wwVKsjx6
> […](#)

Ok that seems to have worked fine, I may update the log to display systems being added. 

Can you send me the gamelist.xml of the problem systems?

**Comment by Knehall1** [comment]
final burn legends
mame
n64
pcengine 16
sega cd
turbo grafx cd

**Comment by Knehall1** [comment]
the cd based emulators scan bin and cue or cue and iso to make duplicates.
they were originally folderized by emustation when i originally uploaded
them. now they wont scan if they are in individual folders. so i put all
files of each rom set in the individual rom folder they should be in.
they now scan but show every iso or bin

**Comment by Rocky5** [comment]
> the cd based emulators scan bin and cue or cue and iso to make duplicates. they were originally folderized by emustation when i originally uploaded them. now they wont scan if they are in individual folders. so i put all files of each rom set in the individual rom folder they should be in. they now scan but show every iso or bin
> […](#)

Do you have the scan for IOS/Bin/img files enabled under scanner > scanner options?

if so disable it as that’s only used if you’re not using bin/cue files.

**Comment by Knehall1** [comment]
i did have it checked. ran a scan for sega cd, pce cd and turbo cd. sega cd
looks good. the others are in cue/iso/mp3. im thinking i should download a
bin/cue set of each instead.

**Comment by Rocky5** [comment]
> i did have it checked. ran a scan for sega cd, pce cd and turbo cd. sega cd looks good. the others are in cue/iso/mp3. im thinking i should download a bin/cue set of each instead.
> […](#)

Pce-cd and tg-cd are the same emulator just different menu icon and they only support cue/bin files in emustation.

If it’s a CD based system, use bin/cue except for segacd as it ends up 70GB when the ISO/MP3 combos works fine. (Requires you download the emulator from the downloader)

**Comment by Rocky5** [comment]
> Gotcha. Working on a new bin/cue set for those now. Any idea on the other emulators? Do you think i should just delete the emustation folder and reload 1.2 from the xtras disc?
> […](#)

You’re the only one with issues 🙈 I always do a full rescan of all my stuff before I release anything, so I know I haven’t broken anything. 

All my systems scan in file, none have any issues including the ones you have problems with. 

N46 is a pain in my rectum, but once it’s setup it works. 

FBL/Mame you just put rom zips in the fbl and mame folder and run the script and that’s it 😂 they are found and if you installed artwork for them it’s shown. (Synopsis is included with emustation for fbl and mame)

**Comment by Knehall1** [comment]
It was all working just fine. I was installing xbox roms and to my f and g
drives and reslized if i stsrt downloading dlc's to my e drive i was gonna
have a problem. All my emulators were in e drive. I moved them to the f
drive. I updated my custom paths afterwards. I did also delete a bunch of
computer based emulators after the move. Decided on going with arcade,
handhelds and console based emulators. I may have gotten rid of something
accidentally
.

**Comment by Rocky5** [comment]
> It was all working just fine. I was installing xbox roms and to my f and g drives and reslized if i stsrt downloading dlc's to my e drive i was gonna have a problem. All my emulators were in e drive. I moved them to the f drive. I updated my custom paths afterwards. I did also delete a bunch of computer based emulators after the move. Decided on going with arcade, handhelds and console based emulators. I may have gotten rid of something accidentally .
> […](#)

When moving them dont have them on the root of a partition. (Roms, media and emulators for example) Put then in a root folder if you haven’t, I use XBMC-E Files on F and the roms, media and emulators folders are inside there. Then I point the custom paths to those folders and that’s it’s done. 

Not much has changed for scanning between 1.2 and 1.4 bar refinement and additional systems. 

I need to fix homebrew in other scripts that parses ports and Xbox as those are treated as xbe systems and not roms. But that doesn’t affect the scan or launching scripts.

**Comment by Knehall1** [comment]
so i did what you recommended. i moved my emustation folder from e: drive
to f: drive. placed my emulators back into the emustation/emulators folder.
updated my custom paths. did a rescan of all systems. everything is back
where it should be. games scan in perfect. artwork and synopsis files are
as they should. fbl and mame load and run games. my cd based emulators
created proper folders for games. even the notorious n64 emulator is good
to go.

thanks so much for helping me sort this out.

as always i commend you and others for your great work.

**Comment by Rocky5** [comment]
Brilliant 😁 yeah Python doesn’t like the folders on to root of the partitions for some reason.

But am happy it’s working as should 😁 have fun in emustation 😂
