### ISSUE TITLE
Whenever I load a game or rom, there's a chance that I'll get stuck with a black screen

### ISSUE THREAD

**Issue by jksherk** [Rocky5/XBMC-Emustation#84]
I've been using the XBMC-emustation for several days now, and I must say it's a fantastic dashboard. However, I've been experiencing a issue where I randomly encounter a black screen after loading a game or ROM. Do you happen to have any solutions for this?

here is a log, I loaded nes rom battle tank, and after that I got a black-screen

/
11:05:11 M: 89300992  NOTICE: DVDPlayer: Opening: F:\Emu\media\nes/videos/battle tank.xmv
11:05:11 M: 89300992 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:05:11 M: 88776704  NOTICE: Creating InputStream
11:05:12 M: 88776704  NOTICE: Creating Demuxer
11:05:12 M: 88719360  NOTICE: Opening video stream: 0 source: 256
11:05:12 M: 88719360  NOTICE: Creating video codec with codec id: 19
11:05:12 M: 88719360  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: wmv2
11:05:12 M: 88616960  NOTICE: Creating video thread
11:05:12 M: 88092672  NOTICE: Opening audio stream: 1 source: 256
11:05:12 M: 88092672  NOTICE: Finding audio codec for: 69633
11:05:12 M: 87900160  NOTICE: running thread: video_thread
11:05:12 M: 87900160  NOTICE: Creating audio thread
11:05:12 M: 87379968  NOTICE: running thread: CDVDPlayerAudio::Process()
11:05:12 M: 87207936  NOTICE:  fps: 29.970030, pwidth: 256, pheight: 224, dwidth: 256, dheight: 224
11:05:12 M: 87191552  NOTICE: Creating audio device with codec id: 69633, channels: 2, sample rate: 32000, no pass-through
11:05:12 M: 87142400  NOTICE: Display resolution USER : 720p 16:9 (1)
11:05:12 M: 87003136   ERROR: CDVDAudio::AddPackets - failed to add leftover bytes to render
11:05:13 M: 86859776  NOTICE: CDVDPlayer::CloseFile()
11:05:13 M: 86859776  NOTICE: DVDPlayer: waiting for threads to exit
11:05:13 M: 86859776  NOTICE: CDVDPlayer::OnExit()
11:05:13 M: 86859776  NOTICE: DVDPlayer: closing audio stream
11:05:13 M: 86859776  NOTICE: Closing audio stream
11:05:13 M: 86859776  NOTICE: Waiting for audio thread to exit
11:05:13 M: 86859776   ERROR: CDVDAudio::AddPackets - failed to add leftover bytes to render
11:05:13 M: 86859776  NOTICE: thread end: CDVDPlayerAudio::OnExit()
11:05:13 M: 87384064  NOTICE: Closing audio device
11:05:13 M: 87416832  NOTICE: Deleting audio codec
11:05:13 M: 87621632  NOTICE: DVDPlayer: closing video stream
11:05:13 M: 87621632  NOTICE: Closing video stream
11:05:13 M: 87621632  NOTICE: waiting for video thread to exit
11:05:13 M: 87621632  NOTICE: thread end: video_thread
11:05:13 M: 88162304  NOTICE: deleting video codec
11:05:13 M: 88485888  NOTICE: CDVDPlayer::OnExit() deleting demuxer
11:05:13 M: 88518656  NOTICE: CDVDPlayer::OnExit() deleting input stream
11:05:13 M: 89042944  NOTICE: DVDPlayer: finished waiting
11:05:13 M: 89841664  NOTICE: CDVDPlayer::CloseFile()
11:05:13 M: 89841664 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:05:13 M: 89841664  NOTICE: DVDPlayer: waiting for threads to exit
11:05:13 M: 89841664  NOTICE: DVDPlayer: finished waiting
11:05:13 M: 89858048  NOTICE: CDVDPlayerVideo::~CDVDPlayerVideo - uninitting video device
11:05:16 M: 97435648  NOTICE: Storing total System Uptime
11:05:16 M: 97435648  NOTICE: Saving settings
11:05:16 M: 97435648  NOTICE: stop all
11:05:16 M: 97435648  NOTICE: stop dvd detect media
11:05:16 M: 97501184  NOTICE: stop fancontroller
11:05:16 M: 97501184  NOTICE: stop daap clients
11:05:16 M: 97501184  NOTICE: clean cached files!
11:05:16 M: 97501184  NOTICE: unload skin
11:05:16 M: 98922496   ERROR: CLocalizeStrings::ClearBlock: Trying to clear non existent block Q:\emustation\scripts
Previous line repeats 1 times.
11:05:16 M:101138432   ERROR: CGUITextureManager::Cleanup: Having to cleanup texture background diffuse.png
11:05:16 M:102584320  NOTICE: stop python
11:05:16 M:102694912   ERROR: CLocalizeStrings::ClearBlock: Trying to clear non existent block Q:\emustation\scripts
11:05:16 M:103063552   FATAL: EXCEPTION_BREAKPOINT (0x80000003)
                                             at 0x003fe443

**Comment by Rocky5** [comment]
If you’re using the video layout (as a video was playing so I assume you were) try it in another layout type. 

It’s an actual crash when trying to unload the scripts.

the video mode was never 100% as it was hacked together in python 😂🙈 instead of doing it properly in C++.

**Comment by jksherk** [comment]
Thank you for the quick response. I've been using the video layout, but I'm going to try a different layout to see if it makes a difference. However, I've noticed that some Xbox games don't have video previews, and occasionally when I try to load them, I'm faced with a black screen. It's strange because after a reboot, the game runs OK without any issues. Do you happen to know why this happens?

**Comment by Rocky5** [comment]
It’s probably memory of some kind. Since am loading multiple scripts to do stuff it all adds up and the Xbox well wasn’t designed nor was XBMC 😂 (it has to exit one script to load another)

Video mode works, but it’s not 100% stable, though I haven’t had any issues. But I don’t launch that many games as I don’t play them.

**Comment by jksherk** [comment]
I changed the layout and it seems to have solved the issue. Thanks again for your help! I've been using xbmc-emustation a lot lately, and I haven't experienced a single black screen. It's working great!

**Comment by Rocky5** [comment]
> I changed the layout and it seems to have solved the issue. Thanks again for your help! I've been using xbmc-emustation a lot lately, and I haven't experienced a single black screen. It's working great!

Greats 🙏😁
