### ISSUE TITLE
English strings.po in current download has incorrect line endings

### ISSUE THREAD

**Issue by dacrossman** [Rocky5/XBMC-Emustation#85]
Hi!

Current Version being v1.4.004 available at: https://drive.google.com/open?id=1timqZv2wJJRTf68BrvY5rkubnq1Thcs4 

Had a strange issue where the "Start" menu (Custom_Menu.xml) and several items in Settings (Settings.xml) were coming up blank on a fresh install of XBMC-Emustation. Pictures attached. (CRT's are hard to take pics of!)

I found an issue in the debug log of:

14:27:38 M: 47816704   DEBUG: POParser: PO file has Mac Style Line Endings. Converted in memory to Linux LF for file: Q:\emustation\themes\simple\language\English\strings.po                                      
103 14:27:38 M: 47796224   DEBUG: POParser: loaded 0 strings from file Q:\emustation\themes\simple\language\English\strings.po

I ran the dos2unix tool against strings.po and uploaded to the Xbox and now my menu items appear! 

I'm not sure why this affected only me it seems as I couldn't find anyone else having issues. My Xbox is a PAL v1.4, TSOP modded running Cerbios in NTSC Mode, with a 2TB HDD+Startech adapter. 

![IMG_1217](https://user-images.githubusercontent.com/1145707/231974956-5f72f863-f0fe-4e07-bd3f-af4a5b89063a.jpg)
![IMG_1215](https://user-images.githubusercontent.com/1145707/231975387-edc7d236-a2a0-4ffa-9a9f-f5ddcfe0e55d.jpg)

**Comment by Rocky5** [comment]
More than likely it was your FTP program that done something to text files. (FileZilla can corrupt files if transfer mode isn’t set to binary)

As like you said never heard of anyone having this issue 🙈

But you got it sorted 😁
