### ISSUE TITLE
update 1.4.006

### ISSUE THREAD

**Issue by Knehall1** [Rocky5/XBMC-Emustation#87]
i updated my 1.4v console to latest update of emustation as of 2 hours ago. so much is not working right now. no media will show up in the rom lists....boxart, 3d boxart, screenshot,etc. the rom lists show the correct number of roms per emulutor on the carousel but only shows the xbox games i have on my box. thats every emulator list. ive tried to change themes but most dont work or simply doesnt load correctly. ive tried to rescan roms for about 5 of the systems with no luck. still shows the xbox games. ive checked the roms and media paths. reset them to default and changed them back. 
roms=f:\roms
media=f:\media

also my text is really kinda large now in  my menus. not sure if this is the norm now with the new update.

**Comment by Rocky5** [comment]
Please move your F:\roms\ to F:\XBMC-Emu Fikes\roms\

Same with any other custom paths and update your paths in the settings menu. 

Having them on the root of a partition causes issues due to python in XBMC.

**Comment by Knehall1** [comment]
![20230710_043922](https://github.com/Rocky5/XBMC-Emustation/assets/124131372/59c62464-bcb6-4a84-b85a-38ff48a1b93a)
![20230710_043936](https://github.com/Rocky5/XBMC-Emustation/assets/124131372/0692dcb2-8814-481a-90df-67dfdd745cc8)
![20230710_043954](https://github.com/Rocky5/XBMC-Emustation/assets/124131372/34212359-65ae-4a1a-b518-4617f5c2f71c)
![20230710_044031](https://github.com/Rocky5/XBMC-Emustation/assets/124131372/9283301d-f548-4900-b7c2-e9c340539d75)
![20230710_044120](https://github.com/Rocky5/XBMC-Emustation/assets/124131372/b6b22b0c-a23d-4891-83cf-7bb15a7ee2b5)

**Comment by Knehall1** [comment]
i tried to load up some gamed to the virtual boy folder under the emustation folder structure. changed the custom path to reflect that. ran a scan. carousel showed 13 games. but when i click on the virtual boy icon to enter the rom list, it shows the same xbox games as in the picture for the atari 2600

**Comment by Knehall1** [comment]
its set for US. i live in the US

**Comment by Rocky5** [comment]
OK I see now, will fix it. It its not updating the game lists.

**Comment by Knehall1** [comment]
do i still need to run the file you sent me?

**Comment by Rocky5** [comment]
> do i still need to run the file you sent me?

no no.

**Comment by Knehall1** [comment]
so if im using a composite cable im stuck with the big text. only option to fix that would be to change cables to a component cable or hdmi converter correct?

any possible way to revert back to a previous version of emustation?

as far as fixing the current version, prolly get it updated sometime in the near future?

**Comment by Rocky5** [comment]
> so if im using a composite cable im stuck with the big text. only option to fix that would be to change cables to a component cable or hdmi converter correct?

Correct, alternativly you can just remove the "emustation/themes/simple/xml_sd_ntsc" folder and it will use the old method and fix your large test issue.

> any possible way to revert back to a previous version of emustation?

Grab the prebuilt version from here, I haven't updated that version yet so its still 1.4.004

> as far as fixing the current version, prolly get it updated sometime in the near future?

Will be uploaded shorty, same version number but with the fixes.

**Comment by Rocky5** [comment]
OK can you update again, I fixed all the issues you had and also added a toggle under Menu>UISettings to disable the SD resolution support.

**Comment by Knehall1** [comment]
updated to 1.4.006. it appears everything is back up and running. the SD off feature did the trick with the large text. very smooth transition. i can see that coming in handy if you have a widescreen tv and a crt and wanted to switch between them from time to time. i did notice however if the SD Resolution feature is active, other themes load wonky or dont load at all. once its disabled, the other themes load correctly. i know you stated the feature was primarily for the simple theme.  the game lists are updated correctly showing correct roms and artwork. all in all i say you its good to go. Thanks as always for all you do.

**Comment by Rocky5** [comment]
> updated to 1.4.006. it appears everything is back up and running. the SD off feature did the trick with the large text. very smooth transition. i can see that coming in handy if you have a widescreen tv and a crt and wanted to switch between them from time to time. i did notice however if the SD Resolution feature is active, other themes load wonky or dont load at all. once its disabled, the other themes load correctly. i know you stated the feature was primarily for the simple theme. the game lists are updated correctly showing correct roms and artwork. all in all i say you its good to go. Thanks as always for all you do.

Great 😁 thank you for spotting the issue as I didn’t on my test box 🙈 and I thought it would be more user friendly to add a toggle instead of making people remove folders to do it. 

But am glad it’s sorted and no more issues. Thanks again for letting me know so I could fix it.
