### ISSUE TITLE
URLDownloader broken in latest build.

### ISSUE THREAD

**Issue by loggio** [Rocky5/XBMC-Emustation#89]
latest update breaks url downloader. 

when i launch downloader, dialog appears saying "Download" URLDownloader.zip.
I click "Yes" it downloads and installs. 
Then it loads the same dialog asking me to download and install again. 

it's on an endless loop.

**Comment by Rocky5** [comment]
> latest update breaks url downloader.
> 
> when i launch downloader, dialog appears saying "Download" URLDownloader.zip. I click "Yes" it downloads and installs. Then it loads the same dialog asking me to download and install again.
> 
> it's on an endless loop.

You should only need to do it twice. Since I had to change the drive that stored all the files I had to make the old downloader point to this one. 

I have 3 drives, the old one points to my personal drive and that points to the new drive. (Hence you may have to do it twice)

You can try running the force update button at the bottom, this will always download from my personal drive.

**Comment by Rocky5** [comment]
Wait you see the same, dialog with yes or no to download the zip?

those files should be replaced. You should be told it’s updated and it should reload.

**Comment by loggio** [comment]
maybe something to do with SD res?

**Comment by loggio** [comment]
> Wait you see the same, dialog with yes or no to download the zip?
> 
> those files should be replaced. You should be told it’s updated and it should reload.
> 
> Oh I know why, you’re in SD mode.
> 
> will fix it.

nice!

**Comment by Rocky5** [comment]
Try now

**Comment by loggio** [comment]
> Reference

perfect. working now mate. Cheers

**Comment by Rocky5** [comment]
> > Reference
> 
> perfect. working now mate. Cheers

could you update to the test build and let me know if everything is working as it should be please?

I have changed some menus etc... so I had to update the sd files also.

**Comment by loggio** [comment]
updating as we speak. I'll report back later, heading to work now.

**Comment by loggio** [comment]
okay, all your updates seem to work fine. Only thing i'm noticing is with scanning.
If there are .txt or .png files inside a roms folder then they are scanned into that systems rom list. 

So scanner seems to be adding any file extension into the rom list.

**Comment by Rocky5** [comment]
> okay, all your updates seem to work fine. Only thing i'm noticing is with scanning. If there are .txt or .png files inside a roms folder then they are scanned into that systems rom list.
> 
> So scanner seems to be adding any file extension into the rom list.

Scanning looks for extension using the extension files. So any file that’s in there will be added if present in the roms folder. 

Zips are recommended for systems if supported. (Most none cd one are)

**Comment by loggio** [comment]
yeah fair enough. I'm cleaning my roms folders now.  funny, it never did it in the past as i've scanned my roms folders countless times over the last year.

**Comment by Rocky5** [comment]
> yeah fair enough. I'm cleaning my roms folders now. funny, it never did it in the past as i've scanned my roms folders countless times over the last year.

https://github.com/Rocky5/XBMC-Emustation/tree/master/Mod%20Files/emustation/scripts/rom_extensions

Yeah .txt ain’t there so those shouldn’t be scanned. 

I will need to see what I done 😂 but won’t be for 5 or 6 days before I can. 

But I never touched the extension stuff 😬
