### ISSUE TITLE
Permanent Ports Carousel Tile

### ISSUE THREAD

**Issue by dbrown1986** [Rocky5/XBMC-Emustation#9]
Updated to latest via built-in downloader.
Ports carousel tile is present w/ no ports or homebrew games installed within proper folder.
Text below the tile is truncated.

Can provide picture if necessary.

I have deleted my XBMC folder and its corresponding UDATA folder and reinstalled from the pre-built download, still there.

Going to test what happens if I put a game in the folder.

**Comment by Rocky5** [comment]
Send image please.

**Comment by evertonstz** [comment]
I'm also having this bug, heres a picture. [https://i.imgur.com/gTE6k1u.jpg](url)

**Comment by dbrown1986** [comment]
Mine is identical to evertonstz, except I'm using the XBMC4Gamers style.
[https://i.imgur.com/sW3BjPI.jpg](https://i.imgur.com/sW3BjPI.jpg)

**Comment by Rocky5** [comment]
add something to E,F or G Ports or Homebrew and refresh the carousel.

Will fix it soon its just a visible tag issue.

**Comment by Rocky5** [comment]
Issues is fixed, update in an hour or so.

Art Book or XBMC4Gamers themes need to be redownloaded. Main XBMC-Emustation has a new update.
