### ISSUE TITLE
Synopsis Naming

### ISSUE THREAD

**Issue by DustyBin1980** [Rocky5/XBMC-Emustation#90]
Hi I cant get the synopsis naming to work I have run the artwork installer a few times set it to use resources for artwork and to use synopsis naming and all my games still have (USA) etc.. after the game name.

If I enter edit XBE mode and edit it its fine until I exit XBE edit mode and then it changes back to having (USA) etc.. after the game name.

**Comment by Rocky5** [comment]
Stable or test build?

Synopsis naming uses the games titleids to pull the info from the synopsis files, “Q:\emustation\synopsis\xbox\” make sure that folder has over 1000 txt files. 

Download the test build and see if that fixes the issue as I have changed a few things in that version regarding menus and functioning of the creat roms script.

**Comment by DustyBin1980** [comment]
Stable build mate synopsis folder has 1085 txt files in in it.

Rescanned using the manual scan mode and it sorted it mate as always thanks for your help and all you do for the scene to keep it alive man.

**Comment by Rocky5** [comment]
> Stable build mate synopsis folder has 1085 txt files in in it.
> 
> Rescanned using the manual scan mode and it sorted it mate as always thanks for your help and all you do for the scene to keep it alive man.

Glad you got it sorted, but I still recommend updating to the test build 😂

A lot of improvements and QOL additions. 

Themes won’t work on this version but I can link you to one that I have made using the new features & include variables. If you want to try it out for me and give feedback?
