### ISSUE TITLE
RetroAchievements

### ISSUE THREAD

**Issue by ahrimanes** [Rocky5/XBMC-Emustation#91]
this is not an issue but more of a request!!!

since it seems retroarch and his awesome RetroAchievements support is not on OG XBOX is there a chanse XBMC-Emustation can integrate it some how??.. I understand emulators are individual apps... but... can we dream of it ??

**Comment by Rocky5** [comment]
Not possible unfortunately, I wouldn’t even know where to start and in retroarch it’s added to the emulator corse and even then not all support it. 

Sorry.
