### ISSUE TITLE
480p for dark summit 

### ISSUE THREAD

**Issue by filevans** [Rocky5/XBMC-Emustation#94]
Hello, please do you have the hex code to patch dark summit to 480p to work on a 1.6 Xbox? I know I can use the XBMC script to patch it but I like to use unleashx to launch games so I would like to be able to patch the dark summit xbe directly if possible? Thank you very much

**Comment by Rocky5** [comment]
Wrong repository.

http://web.archive.org/web/20101201095646/wiki-scene.com/Xbox_Enable_Progressive_Scan_(480p)
