### ISSUE TITLE
MameOXtras Decade 2023 loading issue

### ISSUE THREAD

**Issue by ComicbookGuy70** [Rocky5/XBMC-Emustation#95]
Hi, fantastic software!  Changes the whole game.  Thank you for the effort.

So, odd issue. I upgraded to the newest release and also then upgraded to MameXtras Decade 2023. Everything seems find but the autolaunch loads the first rom in the list no matter which is chosen. Like it defaults to the first.  Any suggestions?  Thanks

**Comment by Rocky5** [comment]
Where are your roms located?
