### ISSUE TITLE
ERROR: Google Drive issue. Probably exceeded daily download quota.

### ISSUE THREAD

**Issue by rustiferch** [Rocky5/XBMC-Emustation#96]
Hi Team,
Just checking if there are known issues with the URL Downloader at the moment? I've been trying to download it for about a week now and keep getting the below error:

ERROR: Google Drive issue. Probably exceeded daily download quota.
Wait a couple of hours are try again.

XBMC-Emustation v1.4.004
URL Downloader v1.0.36

**Comment by Rocky5** [comment]
No, if you’re were on the old server then you won’t be able to update to the new server now. There was a 2 month grace period for everyone to move over and u fortunately if you missed it (now 3 months) then you need to grab the forceupdate.py from here and run it on the Xbox. 

I didn’t update the link with the latest version 1.4.006, it’s now been updated. 

But grabbing the forceupdate.py and running it will fix your issue and let you update to the latest stable or test build.

**Comment by rustiferch** [comment]
Great - I'll download the latest build and grab out the forceupdate.py. Thanks :)

**Comment by rustiferch** [comment]
No good. I downloaded from Github link, copied the emustation\scripts\urldownloader folder to the same spot on my xbox and then ran the forceupdate.py from file explorer but it's not doing anything.

Is it hard to manually upgrade without losing settings?

**Comment by Rocky5** [comment]
> Great - I'll download the latest build and grab out the forceupdate.py. Thanks :)

Grab it now, I didn’t update the forceupdate.py 🙈 was pointing to the wrong location 😑

**Comment by rustiferch** [comment]
Ok, I'll give it another go :)

**Comment by PossumSmoj** [comment]
how'd you go, Rusti?
At my end I'm not yet seeing anything newly updated since 3 months ago.
