### ISSUE TITLE
Downloader (URLDownloader.zip) 404 Not Found (v1.4.006)

### ISSUE THREAD

**Issue by calebTree** [Rocky5/XBMC-Emustation#97]
On version 1.4.006 I get `404 Not Found` attempting to download the "URLDownloader.zip" (install size 2.99 MB), after the "attempting to resolve google drive link" dialog. I've used the downloader to get to this version (so downloader was working in previous version) and I've re-installed many times however as soon as `1.4.006` is finished installing the URLDownloader.zip ends up 404 Not Found.
Just to be fancy, this is the SHA1 of the .xbe (not sure if this is relevant as I have compared it to the latest release and it matches):
```
SHA1 hash of default.xbe:
f502bbb1e421722f91b3c3ea16deebf2b4d6e606
```

**Comment by Rocky5** [comment]
Just checked the files and no issue. They point to the correct location for files. 

Download the pre built version from the readme.md file on here. Extract the “XBMC-Enustation\emustation\scripts\URLDownloader” folder and overwrite the one in your install. 

Run the downloader now and see if it loads. If not make sure you have an alt DNS if you’re using insignias DNS. (Downloader won’t work if you don’t)

**Comment by calebTree** [comment]
Thanks for pointing out where the relevant scripts are.
The urldownloader version installed was apparently `1.0.36`. The version in the latest from the README.md is `1.0.31`. I replaced the whole folder, and the error became: `ERROR Google Drive issue. Probably exceeded daily download quota. Wait a couple hours and try again.`

**Comment by Rocky5** [comment]
> Thanks for pointing out where the relevant scripts are. The urldownloader version installed was apparently `1.0.36`. The version in the latest from the README.md is `1.0.31`. I replaced the whole folder, and the error became: `ERROR Google Drive issue. Probably exceeded daily download quota. Wait a couple hours and try again.`

You’re not v1.4.006 you may have updated to v1.4.004 as I forgot to update the downloader files other that the test build files. 

The was all corrected, recently.

**Comment by calebTree** [comment]
Perfect, thanks a ton, I didn't know I could run a script from File Manager. I did have to replace the `emustation/scripts/urldownloader` folder then ForceUpdate.py worked.
- As a note, this was a 1.0 Xbox, with the Stellar hardmod. I used the Softmod Extras 1.1.9 disk to install Emustation.

**Comment by Rocky5** [comment]
> Perfect, thanks a ton, I didn't know I could run a script from File Manager. I did have to replace the `emustation/scripts/urldownloader` folder then ForceUpdate.py worked.
> 
> * As a note, this was a 1.0 Xbox, with the Stellar hardmod. I used the Softmod Extras 1.1.9 disk to install Emustation.

Yeah I haven’t updated the build on there it seems 🙈 life man 😑😁

will need to do it, but that won’t fix folk who have already installed as of 2 month ago as the downloader on there won’t work)

**Comment by calebTree** [comment]
Haha, I have no problem helping to find bugs.

**Comment by Rocky5** [comment]
Yeah the advanced menu check for update is decrepit now, need to remove it. 

Update to the test build a lot better than stable 🙏
