### ISSUE TITLE
xbmc4gamers

### ISSUE THREAD

**Issue by Davidrsf** [Rocky5/XBMC-Emustation#99]
Hello Rocky5, first of all sorry for asking here, I know it's not the right place but I didn't find another place to contact you, I would like to know is it possible to enable background music to the xbmc4gamers dash automatically?
For example, does it automatically play music playlist when I log in with my profile?
Thank you very much for your attention

**Comment by Rocky5** [comment]
Music goes in E,F or G:\Music

you goto settings > skin settings > startup options

toggle enable audio playlist > generate random playlist

that’s you.
